
CREATE TABLE COMMON_ORGANIZATION
(
	ORGANIZATION_CODE    VARCHAR2(100) NOT NULL ,
	ORGANIZATION_NAME    NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE COMMON_ORGANIZATION IS 'Danh mục Đơn vị quan hệ ngân sách';




COMMENT ON COLUMN COMMON_ORGANIZATION.ORGANIZATION_CODE IS 'Mã đơn vị quan hệ ngân sách';




COMMENT ON COLUMN COMMON_ORGANIZATION.ORGANIZATION_NAME IS 'Tên đơn vị quan hệ ngân sách';




COMMENT ON COLUMN COMMON_ORGANIZATION.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN COMMON_ORGANIZATION.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN COMMON_ORGANIZATION.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN COMMON_ORGANIZATION.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN COMMON_ORGANIZATION.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN COMMON_ORGANIZATION.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX COMMON_ORGANIZATION_PK ON COMMON_ORGANIZATION
(ORGANIZATION_CODE   ASC);



ALTER TABLE COMMON_ORGANIZATION
	ADD CONSTRAINT  COMMON_ORGANIZATION_PK PRIMARY KEY (ORGANIZATION_CODE);



CREATE TABLE COMMON_STATUS
(
	STATUS_CODE          VARCHAR2(100) NOT NULL ,
	STATUS_NAME          NVARCHAR2(500) NOT NULL ,
	SUB_SYSTEM           VARCHAR2(100) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE COMMON_STATUS IS 'Bảng danh mục trạng thái xử lý';




COMMENT ON COLUMN COMMON_STATUS.STATUS_CODE IS 'Mã trạng thái xử lý';




COMMENT ON COLUMN COMMON_STATUS.STATUS_NAME IS 'Tên trạng thái xử lý: Chưa hoàn thiện, Đã hoàn thiện, Chờ kiểm soát, Từ chối kiểm soát, Hủy kiểm soát, Chờ phê duyệt, Từ chối phê duyệt, Hủy phê duyệt, Hoàn thành xử lý';




COMMENT ON COLUMN COMMON_STATUS.SUB_SYSTEM IS 'Phân hệ hệ thống';




COMMENT ON COLUMN COMMON_STATUS.DESCRIPTION IS 'Mô tả trạng thái xử lý';




COMMENT ON COLUMN COMMON_STATUS.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN COMMON_STATUS.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN COMMON_STATUS.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN COMMON_STATUS.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN COMMON_STATUS.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX COMMON_STATUS_PK ON COMMON_STATUS
(STATUS_CODE   ASC);



ALTER TABLE COMMON_STATUS
	ADD CONSTRAINT  COMMON_STATUS_PK PRIMARY KEY (STATUS_CODE);



CREATE TABLE COMMON_TREASURY
(
	TREASURY_CODE        VARCHAR2(100) NOT NULL ,
	TREASURY_NAME        NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE COMMON_TREASURY IS 'Danh mục Kho bạc';




COMMENT ON COLUMN COMMON_TREASURY.TREASURY_CODE IS 'Mã kho bạc';




COMMENT ON COLUMN COMMON_TREASURY.TREASURY_NAME IS 'Tên kho bạc';




COMMENT ON COLUMN COMMON_TREASURY.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN COMMON_TREASURY.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN COMMON_TREASURY.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN COMMON_TREASURY.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN COMMON_TREASURY.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN COMMON_TREASURY.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX COMMON_TREASURY_PK ON COMMON_TREASURY
(TREASURY_CODE   ASC);



ALTER TABLE COMMON_TREASURY
	ADD CONSTRAINT  COMMON_TREASURY_PK PRIMARY KEY (TREASURY_CODE);



CREATE TABLE EXP_APPROVAL_LOG
(
	ID                   RAW(16) NOT NULL ,
	DOSSIER_ID           RAW(16) NOT NULL ,
	DOSSIER_CODE         VARCHAR2(100) NOT NULL ,
	ACTION_USER          VARCHAR2(100) NOT NULL ,
	ACTION_ROLE          VARCHAR2(100) NOT NULL ,
	ACTION_DATE          DATE NOT NULL ,
	REASON               NVARCHAR2(2000) NOT NULL ,
	STATE_CODE           VARCHAR2(100) NOT NULL ,
	PARENT_ID            RAW(16) NULL ,
	CREATED_DATE         DATE NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_APPROVAL_LOG IS 'Bảng thông tin luồng phê duyệt của hồ sơ';




COMMENT ON COLUMN EXP_APPROVAL_LOG.ID IS 'UUID khóa chính';




COMMENT ON COLUMN EXP_APPROVAL_LOG.DOSSIER_ID IS 'UUID hồ sơ';




COMMENT ON COLUMN EXP_APPROVAL_LOG.ACTION_USER IS 'Người thực hiện';




COMMENT ON COLUMN EXP_APPROVAL_LOG.ACTION_ROLE IS 'Vai trò thực hiện (Maker, Checker, Approver)';




COMMENT ON COLUMN EXP_APPROVAL_LOG.ACTION_DATE IS 'Thời điểm thực hiện';




COMMENT ON COLUMN EXP_APPROVAL_LOG.REASON IS 'Lý do';




COMMENT ON COLUMN EXP_APPROVAL_LOG.STATE_CODE IS 'Trạng thái';




COMMENT ON COLUMN EXP_APPROVAL_LOG.PARENT_ID IS 'ID tham chiếu đến bản ghi APPROVAL_LOG_ID trước';




COMMENT ON COLUMN EXP_APPROVAL_LOG.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_APPROVAL_LOG.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_APPROVAL_LOG.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_APPROVAL_LOG.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_APPROVAL_LOG_PK ON EXP_APPROVAL_LOG
(ID   ASC);



ALTER TABLE EXP_APPROVAL_LOG
	ADD CONSTRAINT  EXP_APPROVAL_LOG_PK PRIMARY KEY (ID);



CREATE TABLE EXP_ATTACHMENT_TYPE
(
	ATTACHMENT_TYPE_CODE VARCHAR2(100) NOT NULL ,
	ATTACHMENT_TYPE_NAME NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_ATTACHMENT_TYPE IS 'Danh mục loại đính kèm';




COMMENT ON COLUMN EXP_ATTACHMENT_TYPE.ATTACHMENT_TYPE_CODE IS 'Mã loại đính kèm';




COMMENT ON COLUMN EXP_ATTACHMENT_TYPE.ATTACHMENT_TYPE_NAME IS 'Tên loại đính kèm (Chứng từ gốc, Hợp đồng, Hóa đơn, Bảng kê, Văn bản khác)';




COMMENT ON COLUMN EXP_ATTACHMENT_TYPE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_ATTACHMENT_TYPE.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_ATTACHMENT_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_ATTACHMENT_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_ATTACHMENT_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_ATTACHMENT_TYPE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_ATTACHMENT_TYPE_PK ON EXP_ATTACHMENT_TYPE
(ATTACHMENT_TYPE_CODE   ASC);



ALTER TABLE EXP_ATTACHMENT_TYPE
	ADD CONSTRAINT  EXP_ATTACHMENT_TYPE_PK PRIMARY KEY (ATTACHMENT_TYPE_CODE);



CREATE TABLE EXP_AUDIT_LOG
(
	ID                   RAW(16) NOT NULL ,
	TABLE_NAME           VARCHAR2(100) NOT NULL ,
	RECORD_ID            VARCHAR2(100) NOT NULL ,
	ACTION_TYPE          VARCHAR2(100) NOT NULL ,
	OLD_VALUE            CLOB NULL ,
	NEW_VALUE            CLOB NOT NULL ,
	USER_ID              VARCHAR2(100) NOT NULL ,
	ACTION_TIMESTAMP     TIMESTAMP NOT NULL ,
	IP_ADDRESS           VARCHAR2(100) NOT NULL 
);



COMMENT ON TABLE EXP_AUDIT_LOG IS 'Bảng ghi log audit của hệ thống';




COMMENT ON COLUMN EXP_AUDIT_LOG.ID IS 'UUID khóa chính';




COMMENT ON COLUMN EXP_AUDIT_LOG.TABLE_NAME IS 'Tên bảng thay đổi';




COMMENT ON COLUMN EXP_AUDIT_LOG.RECORD_ID IS 'ID bản ghi thay đổi';




COMMENT ON COLUMN EXP_AUDIT_LOG.ACTION_TYPE IS 'Loại thay đổi: INSERT / UPDATE / DELETE / APPROVE / REJECT';




COMMENT ON COLUMN EXP_AUDIT_LOG.OLD_VALUE IS 'Giá trị cũ';




COMMENT ON COLUMN EXP_AUDIT_LOG.NEW_VALUE IS 'Giá trị mới';




COMMENT ON COLUMN EXP_AUDIT_LOG.USER_ID IS 'Người thực hiện thay đổi';




COMMENT ON COLUMN EXP_AUDIT_LOG.ACTION_TIMESTAMP IS 'Thời điểm thay đổi';




COMMENT ON COLUMN EXP_AUDIT_LOG.IP_ADDRESS IS 'Địa chỉ IP';



CREATE UNIQUE INDEX EXP_AUDIT_LOG_PK ON EXP_AUDIT_LOG
(ID   ASC);



ALTER TABLE EXP_AUDIT_LOG
	ADD CONSTRAINT  EXP_AUDIT_LOG_PK PRIMARY KEY (ID);



CREATE TABLE EXP_DATA_SOURCE
(
	DATA_SOURCE_CODE     VARCHAR2(100) NOT NULL ,
	DATA_SOURCE_NAME     NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_DATA_SOURCE IS 'Danh mục nguồn gốc hồ sơ (DVC, Thủ công, Chuyển đổi)';




COMMENT ON COLUMN EXP_DATA_SOURCE.DATA_SOURCE_CODE IS 'Mã nguồn gốc hồ sơ';




COMMENT ON COLUMN EXP_DATA_SOURCE.DATA_SOURCE_NAME IS 'Tên nguồn gốc hồ sơ (DVC, Thủ công, Chuyển đổi)';




COMMENT ON COLUMN EXP_DATA_SOURCE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_DATA_SOURCE.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_DATA_SOURCE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DATA_SOURCE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DATA_SOURCE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DATA_SOURCE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DATA_SOURCE_PK ON EXP_DATA_SOURCE
(DATA_SOURCE_CODE   ASC);



ALTER TABLE EXP_DATA_SOURCE
	ADD CONSTRAINT  EXP_DATA_SOURCE_PK PRIMARY KEY (DATA_SOURCE_CODE);



CREATE TABLE EXP_DIGITAL_SIGNED
(
	ID                   RAW(16) NOT NULL ,
	SIGNED_CONTENT       VARCHAR2(2000) NOT NULL ,
	SIGNATURE            VARCHAR2(4000 BYTE) NOT NULL ,
	SIGNATURE_STATUS     NUMBER(1) NOT NULL ,
	CERT                 CLOB NOT NULL ,
	SIGNED_USER          VARCHAR2(100) NOT NULL ,
	SIGNED_ROLE          VARCHAR2(100) NOT NULL ,
	SIGNED_DATE          DATE NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_DIGITAL_SIGNED IS 'Bảng lưu thông tin ký số của hồ sơ';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.ID IS 'UUID phê duyệt';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNED_CONTENT IS 'Thông tin ký số
Định dạng JSON: {documentHash="abc",signerHash="def" algorithm="SHA256"}';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNATURE IS 'Thông tin chữ ký số';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNATURE_STATUS IS 'Trạng thái của chữ ký số: 0-Hết hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.CERT IS 'Thông tin chứng thực ký số';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNED_USER IS 'Người ký';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNED_ROLE IS 'Vai trò ký';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNED_DATE IS 'Ngày ký';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DIGITAL_SIGNED_PK ON EXP_DIGITAL_SIGNED
(ID   ASC);



ALTER TABLE EXP_DIGITAL_SIGNED
	ADD CONSTRAINT  EXP_DIGITAL_SIGNED_PK PRIMARY KEY (ID);



CREATE TABLE EXP_DOCUMENT
(
	ID                   RAW(16) NOT NULL ,
	DOSSIER_ID           RAW(16) NOT NULL ,
	TREASURY_CODE        VARCHAR2(100) NOT NULL ,
	TREASURY_NAME        NVARCHAR2(500) NOT NULL ,
	DOCUMENT_TYPE_CODE   VARCHAR2(100) NOT NULL ,
	DOCUMENT_NAME        NVARCHAR2(500) NOT NULL ,
	DOCUMENT_NO          VARCHAR2(200) NOT NULL ,
	DOCUMENT_DATE        DATE NOT NULL ,
	ACCOUNTING_DATE      DATE NOT NULL ,
	ORIGINAL_AMOUNT      NUMBER(18) NOT NULL ,
	BASE_AMOUNT          NUMBER(18) NOT NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_DOCUMENT IS 'Bảng danh sách thông tin chứng từ theo hồ sơ';




COMMENT ON COLUMN EXP_DOCUMENT.ID IS 'UUID chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT.DOSSIER_ID IS 'UUID hồ sơ';




COMMENT ON COLUMN EXP_DOCUMENT.TREASURY_CODE IS 'Mã kho bạc';




COMMENT ON COLUMN EXP_DOCUMENT.TREASURY_NAME IS 'Tên kho bạc';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_TYPE_CODE IS 'Mã loại chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_NAME IS 'Tên chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_NO IS 'Số chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_DATE IS 'Ngày chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT.ACCOUNTING_DATE IS 'Ngày hạch toán';




COMMENT ON COLUMN EXP_DOCUMENT.ORIGINAL_AMOUNT IS 'Số tiền nguyên tệ';




COMMENT ON COLUMN EXP_DOCUMENT.BASE_AMOUNT IS 'Số tiền VND';




COMMENT ON COLUMN EXP_DOCUMENT.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_DOCUMENT.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOCUMENT.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOCUMENT.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOCUMENT.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DOCUMENT_PK ON EXP_DOCUMENT
(ID   ASC);



ALTER TABLE EXP_DOCUMENT
	ADD CONSTRAINT  EXP_DOCUMENT_PK PRIMARY KEY (ID);



CREATE TABLE EXP_DOCUMENT_ATTACHMENT
(
	ID                   RAW(16) NOT NULL ,
	DOCUMENT_ID          RAW(16) NOT NULL ,
	ATTACHMENT_TYPE_CODE VARCHAR2(100) NOT NULL ,
	FILE_NAME            VARCHAR2(200) NOT NULL ,
	FILE_TYPE            VARCHAR2(100) NOT NULL ,
	FILE_SIZE            DECIMAL(18) NOT NULL ,
	FILE_PATH            VARCHAR2(2000) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_DATE         DATE NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL 
);



COMMENT ON TABLE EXP_DOCUMENT_ATTACHMENT IS 'Bảng thông tin file đính kèm của chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.ID IS 'UUID khóa chính';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.DOCUMENT_ID IS 'Chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.ATTACHMENT_TYPE_CODE IS 'Mã loại đính kèm';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.FILE_NAME IS 'Tên file';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.FILE_TYPE IS 'Loại định dạng file (pdf, jpg, png, docx)';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.FILE_SIZE IS 'Kích thước file';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.FILE_PATH IS 'Đường dẫn file';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.UPDATED_DATE IS 'Ngày cập nhật';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOCUMENT_ATTACHMENT.UPDATED_BY IS 'Người cập nhật';



CREATE UNIQUE INDEX EXP_DOCUMENT_ATTACHMENT_PK ON EXP_DOCUMENT_ATTACHMENT
(ID   ASC);



ALTER TABLE EXP_DOCUMENT_ATTACHMENT
	ADD CONSTRAINT  EXP_DOCUMENT_ATTACHMENT_PK PRIMARY KEY (ID);



CREATE TABLE EXP_DOCUMENT_TYPE
(
	DOCUMENT_TYPE_CODE   VARCHAR2(100) NOT NULL ,
	DOCUMENT_TYPE_NAME   NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_DOCUMENT_TYPE IS 'Danh mục Loại chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.DOCUMENT_TYPE_CODE IS 'Mã loại chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.DOCUMENT_TYPE_NAME IS 'Tên loại chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DOCUMENT_TYPE_PK ON EXP_DOCUMENT_TYPE
(DOCUMENT_TYPE_CODE   ASC);



ALTER TABLE EXP_DOCUMENT_TYPE
	ADD CONSTRAINT  EXP_DOCUMENT_TYPE_PK PRIMARY KEY (DOCUMENT_TYPE_CODE);



CREATE TABLE EXP_DOSSIER
(
	ID                   RAW(16) NOT NULL ,
	TREASURY_CODE        VARCHAR2(100) NOT NULL ,
	TREASURY_NAME        NVARCHAR2(500) NOT NULL ,
	DOSSIER_TYPE_CODE    VARCHAR2(100) NOT NULL ,
	DOSSIER_CODE         VARCHAR2(100) NOT NULL ,
	VERSION              NUMBER(3) NOT NULL ,
	SEND_DATE            DATE NOT NULL ,
	PROJECT_CODE         VARCHAR2(100) NULL ,
	PROJECT_NAME         NVARCHAR2(500) NULL ,
	PROJECT_SPECIFIC_CODE VARCHAR2(100) NULL ,
	PROJECT_SPECIFIC_NAME NVARCHAR2(500) NULL ,
	ORGANIZATION_CODE    VARCHAR2(100) NOT NULL ,
	ORGANIZATION_NAME    NVARCHAR2(500) NOT NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	F_STATUS             VARCHAR2(100) NOT NULL ,
	WORKFLOW_CODE        VARCHAR2(100) NOT NULL ,
	DATA_SOURCE_CODE     VARCHAR2(100) NOT NULL ,
	ASSIGN_USER          VARCHAR2(100) NOT NULL ,
	SLA                  DATE NOT NULL ,
	HASH_INFO            VARCHAR2(2000) NULL ,
	COMPLETED_DATE       DATE NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_DOSSIER IS 'Bảng thông tin hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.ID IS 'UUID khóa chính';




COMMENT ON COLUMN EXP_DOSSIER.TREASURY_CODE IS 'Mã kho bạc';




COMMENT ON COLUMN EXP_DOSSIER.TREASURY_NAME IS 'Tên kho bạc';




COMMENT ON COLUMN EXP_DOSSIER.DOSSIER_TYPE_CODE IS 'Mã loại hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.DOSSIER_CODE IS 'Mã hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.VERSION IS 'Phiên bản hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.SEND_DATE IS 'Ngày gửi hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_CODE IS 'Mã dự án';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_NAME IS 'Tên dự án';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_SPECIFIC_CODE IS 'Mã dự án đặc thù';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_SPECIFIC_NAME IS 'Tên dự án đặc thù';




COMMENT ON COLUMN EXP_DOSSIER.ORGANIZATION_CODE IS 'Mã đơn vị quan hệ ngân sách';




COMMENT ON COLUMN EXP_DOSSIER.ORGANIZATION_NAME IS 'Tên đơn vị quan hệ ngân sách';




COMMENT ON COLUMN EXP_DOSSIER.STATUS IS 'Hiệu lực hồ sơ: 0-Hết hiệu lực, 1-Đang hiệu lực';




COMMENT ON COLUMN EXP_DOSSIER.F_STATUS IS 'Mã trạng thái xử lý hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.WORKFLOW_CODE IS 'Mã luồng phê duyệt';




COMMENT ON COLUMN EXP_DOSSIER.DATA_SOURCE_CODE IS 'Mã loại nguồn dữ liệu';




COMMENT ON COLUMN EXP_DOSSIER.ASSIGN_USER IS 'Người đang xử lý hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.SLA IS 'Thời hạn xử lý theo SLA';




COMMENT ON COLUMN EXP_DOSSIER.HASH_INFO IS 'Thông tin hash của hồ sơ (bao gồm tất cả chứng từ bên trong) khi gửi phê duyệt.
Định dạng JSON: {documentHash="abc", algorithm="SHA256"}';




COMMENT ON COLUMN EXP_DOSSIER.COMPLETED_DATE IS 'Ngày hoàn thành hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOSSIER.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOSSIER.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOSSIER.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DOSSIER_PK ON EXP_DOSSIER
(ID   ASC);



ALTER TABLE EXP_DOSSIER
	ADD CONSTRAINT  EXP_DOSSIER_PK PRIMARY KEY (ID);



CREATE UNIQUE INDEX UK_DOSSIER_VERSION ON EXP_DOSSIER
(DOSSIER_CODE   ASC,VERSION   ASC);



ALTER TABLE EXP_DOSSIER
ADD CONSTRAINT  UK_DOSSIER_VERSION UNIQUE (DOSSIER_CODE,VERSION);



CREATE UNIQUE INDEX UK_DOSSIER_ACTIVE ON EXP_DOSSIER
(CASE WHEN STATUS = 1 THEN DOSSIER_CODE ELSE NULL END   ASC);




ALTER TABLE EXP_DOSSIER
	ADD CONSTRAINT  CHK_DOSSIER_PROJECT CHECK  ((DOSSIER_TYPE_CODE = 'CAPEX' AND PROJECT_CODE IS NOT NULL)
     OR (DOSSIER_TYPE_CODE = 'OPEX' AND PROJECT_CODE IS NULL));



CREATE TABLE EXP_DOSSIER_ATTACHMENT
(
	ID                   RAW(16) NOT NULL ,
	DOSSIER_ID           RAW(16) NOT NULL ,
	ATTACHMENT_TYPE_CODE VARCHAR2(100) NOT NULL ,
	FILE_NAME            VARCHAR2(200) NOT NULL ,
	FILE_TYPE            VARCHAR2(100) NOT NULL ,
	FILE_SIZE            DECIMAL(18) NOT NULL ,
	FILE_PATH            VARCHAR2(2000) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_DATE         DATE NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL 
);



COMMENT ON TABLE EXP_DOSSIER_ATTACHMENT IS 'Bảng thông tin file đính kèm của hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.ID IS 'UUID khóa chính';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.DOSSIER_ID IS 'UUID hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.ATTACHMENT_TYPE_CODE IS 'Mã loại đính kèm';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.FILE_NAME IS 'Tên file';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.FILE_TYPE IS 'Loại định dạng file (pdf, jpg, png, docx)';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.FILE_SIZE IS 'Kích thước file';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.FILE_PATH IS 'Đường dẫn file';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.UPDATED_DATE IS 'Ngày cập nhật';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOSSIER_ATTACHMENT.UPDATED_BY IS 'Người cập nhật';



CREATE UNIQUE INDEX EXP_DOSSIER_ATTACHMENT_PK ON EXP_DOSSIER_ATTACHMENT
(ID   ASC);



ALTER TABLE EXP_DOSSIER_ATTACHMENT
	ADD CONSTRAINT  EXP_DOSSIER_ATTACHMENT_PK PRIMARY KEY (ID);



CREATE TABLE EXP_DOSSIER_DRAFT
(
	ID                   RAW(16) NOT NULL ,
	DOSSIER_ID           RAW(16) NOT NULL ,
	CONTENT              CLOB NOT NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_DOSSIER_DRAFT IS 'Bảng lưu thông tin bản nháp hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_DRAFT.ID IS 'UUID khóa chính';




COMMENT ON COLUMN EXP_DOSSIER_DRAFT.DOSSIER_ID IS 'UUID hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_DRAFT.CONTENT IS 'Nội dung nháp';




COMMENT ON COLUMN EXP_DOSSIER_DRAFT.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_DOSSIER_DRAFT.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOSSIER_DRAFT.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOSSIER_DRAFT.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOSSIER_DRAFT.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DOSSIER_DRAFT_PK ON EXP_DOSSIER_DRAFT
(ID   ASC);



ALTER TABLE EXP_DOSSIER_DRAFT
	ADD CONSTRAINT  EXP_DOSSIER_DRAFT_PK PRIMARY KEY (ID);



CREATE TABLE EXP_DOSSIER_SLA
(
	ID                   RAW(16) NOT NULL ,
	DOSSIER_ID           RAW(16) NOT NULL ,
	ACTION_ROLE          VARCHAR2(100) NOT NULL ,
	ACTION_USER          VARCHAR2(100) NOT NULL ,
	SLA                  DATE NOT NULL ,
	IS_NOTIFY            NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_DOSSIER_SLA IS 'Bảng thông tin SLA của hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_SLA.ID IS 'UUID khóa chính';




COMMENT ON COLUMN EXP_DOSSIER_SLA.DOSSIER_ID IS 'UUID hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_SLA.ACTION_ROLE IS 'Vai trò của người thực hiện';




COMMENT ON COLUMN EXP_DOSSIER_SLA.ACTION_USER IS 'Người thực hiện';




COMMENT ON COLUMN EXP_DOSSIER_SLA.SLA IS 'Thời gian xử lý theo SLA';




COMMENT ON COLUMN EXP_DOSSIER_SLA.IS_NOTIFY IS 'Trạng thái gửi cảnh báo: 0-Chưa gửi, 1-Đã gửi';




COMMENT ON COLUMN EXP_DOSSIER_SLA.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOSSIER_SLA.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOSSIER_SLA.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOSSIER_SLA.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DOSSIER_SLA_PK ON EXP_DOSSIER_SLA
(ID   ASC);



ALTER TABLE EXP_DOSSIER_SLA
	ADD CONSTRAINT  EXP_DOSSIER_SLA_PK PRIMARY KEY (ID);



CREATE TABLE EXP_DOSSIER_TYPE
(
	DOSSIER_TYPE_CODE    VARCHAR2(100) NOT NULL ,
	DOSSIER_TYPE_NAME    NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_DOSSIER_TYPE IS 'Bảng danh mục loại hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_TYPE.DOSSIER_TYPE_CODE IS 'Mã loại hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_TYPE.DOSSIER_TYPE_NAME IS 'Tên loại hồ sơ (Chi đầu tư, Chi thường xuyên)';




COMMENT ON COLUMN EXP_DOSSIER_TYPE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_DOSSIER_TYPE.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_DOSSIER_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOSSIER_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOSSIER_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOSSIER_TYPE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DOSSIER_TYPE_PK ON EXP_DOSSIER_TYPE
(DOSSIER_TYPE_CODE   ASC);



ALTER TABLE EXP_DOSSIER_TYPE
	ADD CONSTRAINT  EXP_DOSSIER_TYPE_PK PRIMARY KEY (DOSSIER_TYPE_CODE);



CREATE TABLE EXP_PROJECT
(
	PROJECT_CODE         VARCHAR2(100) NOT NULL ,
	PROJECT_TYPE_CODE    VARCHAR2(100) NOT NULL ,
	PROJECT_NAME         NVARCHAR2(500) NOT NULL ,
	ORGANIZATION_CODE    VARCHAR2(100) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_PROJECT IS 'Bảng thông tin dự án';




COMMENT ON COLUMN EXP_PROJECT.PROJECT_CODE IS 'Mã dự án';




COMMENT ON COLUMN EXP_PROJECT.PROJECT_TYPE_CODE IS 'Mã loại dự án';




COMMENT ON COLUMN EXP_PROJECT.PROJECT_NAME IS 'Tên dự án';




COMMENT ON COLUMN EXP_PROJECT.ORGANIZATION_CODE IS 'Mã đơn vị quan hệ ngân sách';




COMMENT ON COLUMN EXP_PROJECT.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_PROJECT.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_PROJECT.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_PROJECT.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_PROJECT.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_PROJECT.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_PROJECT_PK ON EXP_PROJECT
(PROJECT_CODE   ASC);



ALTER TABLE EXP_PROJECT
	ADD CONSTRAINT  EXP_PROJECT_PK PRIMARY KEY (PROJECT_CODE);



CREATE TABLE EXP_PROJECT_SPECIFIC
(
	PROJECT_SPECIFIC_CODE VARCHAR2(100) NOT NULL ,
	PROJECT_CODE         VARCHAR2(100) NOT NULL ,
	PROJECT_SPECIFIC_NAME NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_PROJECT_SPECIFIC IS 'Danh mục dự án đặc thù';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.PROJECT_SPECIFIC_CODE IS 'Mã dự án đặc thù';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.PROJECT_CODE IS 'Mã dự án';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.PROJECT_SPECIFIC_NAME IS 'Tên dự án đặc thù';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_PROJECT_SPECIFIC_PK ON EXP_PROJECT_SPECIFIC
(PROJECT_SPECIFIC_CODE   ASC);



ALTER TABLE EXP_PROJECT_SPECIFIC
	ADD CONSTRAINT  EXP_PROJECT_SPECIFIC_PK PRIMARY KEY (PROJECT_SPECIFIC_CODE);



CREATE TABLE EXP_PROJECT_TYPE
(
	PROJECT_TYPE_CODE    VARCHAR2(100) NOT NULL ,
	PROJECT_TYPE_NAME    NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_PROJECT_TYPE IS 'Danh mục loại dự án';




COMMENT ON COLUMN EXP_PROJECT_TYPE.PROJECT_TYPE_CODE IS 'Mã loại dự án';




COMMENT ON COLUMN EXP_PROJECT_TYPE.PROJECT_TYPE_NAME IS 'Tên loại dự án (Thường, Đặc thù)';




COMMENT ON COLUMN EXP_PROJECT_TYPE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_PROJECT_TYPE.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_PROJECT_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_PROJECT_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_PROJECT_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_PROJECT_TYPE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_PROJECT_TYPE_PK ON EXP_PROJECT_TYPE
(PROJECT_TYPE_CODE   ASC);



ALTER TABLE EXP_PROJECT_TYPE
	ADD CONSTRAINT  EXP_PROJECT_TYPE_PK PRIMARY KEY (PROJECT_TYPE_CODE);



CREATE TABLE EXP_WORKFLOW
(
	WORKFLOW_CODE        VARCHAR2(100) NOT NULL ,
	WORKFLOW_NAME        NVARCHAR2(500) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NOT NULL ,
	CREATED_BY           VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NOT NULL ,
	UPDATED_DATE         DATE NOT NULL 
);



COMMENT ON TABLE EXP_WORKFLOW IS 'Bảng danh mục luồng phê duyệt';




COMMENT ON COLUMN EXP_WORKFLOW.WORKFLOW_CODE IS 'Mã luồng phê duyệt';




COMMENT ON COLUMN EXP_WORKFLOW.WORKFLOW_NAME IS 'Tên luồng phê duyệt';




COMMENT ON COLUMN EXP_WORKFLOW.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_WORKFLOW.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_WORKFLOW.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_WORKFLOW.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_WORKFLOW.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_WORKFLOW.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_WORKFLOW_PK ON EXP_WORKFLOW
(WORKFLOW_CODE   ASC);



ALTER TABLE EXP_WORKFLOW
	ADD CONSTRAINT  EXP_WORKFLOW_PK PRIMARY KEY (WORKFLOW_CODE);



ALTER TABLE EXP_APPROVAL_LOG
	ADD (CONSTRAINT FK_APPROVAL_LOG_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (ID));



ALTER TABLE EXP_DIGITAL_SIGNED
	ADD (CONSTRAINT FK_DIGITAL_SIGNED_APPROVAL_LOG FOREIGN KEY (ID) REFERENCES EXP_APPROVAL_LOG (ID));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT FK_DOCUMENT_DOCUMENT_TYPE FOREIGN KEY (DOCUMENT_TYPE_CODE) REFERENCES EXP_DOCUMENT_TYPE (DOCUMENT_TYPE_CODE));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT FK_DOCUMENT_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (ID));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT FK_DOCUMENT_TREASURY FOREIGN KEY (TREASURY_CODE) REFERENCES COMMON_TREASURY (TREASURY_CODE));



ALTER TABLE EXP_DOCUMENT_ATTACHMENT
	ADD (CONSTRAINT FK_ATTACHMENT_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES EXP_DOCUMENT (ID));



ALTER TABLE EXP_DOCUMENT_ATTACHMENT
	ADD (CONSTRAINT FK_DOCUMENT_ATTACHMENT_TYPE FOREIGN KEY (ATTACHMENT_TYPE_CODE) REFERENCES EXP_ATTACHMENT_TYPE (ATTACHMENT_TYPE_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT FK_DOSSIER_DATA_SOURCE FOREIGN KEY (DATA_SOURCE_CODE) REFERENCES EXP_DATA_SOURCE (DATA_SOURCE_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT FK_DOSSIER_STATUS FOREIGN KEY (F_STATUS) REFERENCES COMMON_STATUS (STATUS_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT FK_DOSSIER_WORKFLOW FOREIGN KEY (WORKFLOW_CODE) REFERENCES EXP_WORKFLOW (WORKFLOW_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT FK_DOSSIER_PROJECT FOREIGN KEY (PROJECT_CODE) REFERENCES EXP_PROJECT (PROJECT_CODE) ON DELETE SET NULL);



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT FK_DOSSIER_TREASURY FOREIGN KEY (TREASURY_CODE) REFERENCES COMMON_TREASURY (TREASURY_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT FK_DOSSIER_PROJECT_SPECIFIC FOREIGN KEY (PROJECT_SPECIFIC_CODE) REFERENCES EXP_PROJECT_SPECIFIC (PROJECT_SPECIFIC_CODE) ON DELETE SET NULL);



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT FK_DOSSIER_ORGANIZATION FOREIGN KEY (ORGANIZATION_CODE) REFERENCES COMMON_ORGANIZATION (ORGANIZATION_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT FK_DOSSIER_DOSSIER_TYPE FOREIGN KEY (DOSSIER_TYPE_CODE) REFERENCES EXP_DOSSIER_TYPE (DOSSIER_TYPE_CODE));



ALTER TABLE EXP_DOSSIER_ATTACHMENT
	ADD (CONSTRAINT FK_DOSSIER_ATTACHMENT_TYPE FOREIGN KEY (ATTACHMENT_TYPE_CODE) REFERENCES EXP_ATTACHMENT_TYPE (ATTACHMENT_TYPE_CODE));



ALTER TABLE EXP_DOSSIER_ATTACHMENT
	ADD (CONSTRAINT FK_ATTACHMENT_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (ID));



ALTER TABLE EXP_DOSSIER_DRAFT
	ADD (CONSTRAINT FK_DOSSIER_DRAFT_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (ID));



ALTER TABLE EXP_DOSSIER_SLA
	ADD (CONSTRAINT FK_DOSSIER_SLA_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (ID));



ALTER TABLE EXP_PROJECT
	ADD (CONSTRAINT FK_PROJECT_PROJECT_TYPE FOREIGN KEY (PROJECT_TYPE_CODE) REFERENCES EXP_PROJECT_TYPE (PROJECT_TYPE_CODE));



ALTER TABLE EXP_PROJECT
	ADD (CONSTRAINT FK_PROJECT_ORGANIZATION FOREIGN KEY (ORGANIZATION_CODE) REFERENCES COMMON_ORGANIZATION (ORGANIZATION_CODE));



ALTER TABLE EXP_PROJECT_SPECIFIC
	ADD (CONSTRAINT FK_PROJECT_SPECIFIC_PROJECT FOREIGN KEY (PROJECT_CODE) REFERENCES EXP_PROJECT (PROJECT_CODE));


