
CREATE TABLE AUDIT_LOG
(
	AUDIT_LOG_ID         INTEGER NOT NULL 
);



CREATE UNIQUE INDEX AUDIT_LOG_PK ON AUDIT_LOG
(AUDIT_LOG_ID   ASC);



ALTER TABLE AUDIT_LOG
	ADD CONSTRAINT  AUDIT_LOG_PK PRIMARY KEY (AUDIT_LOG_ID);



CREATE TABLE COMMON_ALLOCATION_CRITERIA
(
	ALLOCATION_CRITERIA_CODE VARCHAR2(100) NOT NULL ,
	ALLOCATION_CRITERIA_NAME NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_ALLOCATION_CRITERIA IS 'Tiêu thức phân bổ';




COMMENT ON COLUMN COMMON_ALLOCATION_CRITERIA.ALLOCATION_CRITERIA_CODE IS 'Mã tiêu thức phân bổ';




COMMENT ON COLUMN COMMON_ALLOCATION_CRITERIA.ALLOCATION_CRITERIA_NAME IS 'Tên tiêu thức phân bổ';




COMMENT ON COLUMN COMMON_ALLOCATION_CRITERIA.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_ALLOCATION_CRITERIA_PK ON COMMON_ALLOCATION_CRITERIA
(ALLOCATION_CRITERIA_CODE   ASC);



ALTER TABLE COMMON_ALLOCATION_CRITERIA
	ADD CONSTRAINT  COMMON_ALLOCATION_CRITERIA_PK PRIMARY KEY (ALLOCATION_CRITERIA_CODE);



CREATE TABLE COMMON_BANK
(
	BANK_CODE            VARCHAR2(100) NOT NULL ,
	BANK_NAME            NVARCHAR2(500) NULL 
);



COMMENT ON TABLE COMMON_BANK IS 'Danh mục ngân hàng';




COMMENT ON COLUMN COMMON_BANK.BANK_CODE IS 'Mã ngân hàng';




COMMENT ON COLUMN COMMON_BANK.BANK_NAME IS 'Tên ngân hàng';



CREATE UNIQUE INDEX COMMON_BANK_PK ON COMMON_BANK
(BANK_CODE   ASC);



ALTER TABLE COMMON_BANK
	ADD CONSTRAINT  COMMON_BANK_PK PRIMARY KEY (BANK_CODE);



CREATE TABLE COMMON_GL_SEGMENT10
(
	SEGMENT_CODE         VARCHAR2(100) NOT NULL ,
	SEGMENT_NAME         NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_GL_SEGMENT10 IS 'CTMT';




COMMENT ON COLUMN COMMON_GL_SEGMENT10.SEGMENT_CODE IS 'Mã Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT10.SEGMENT_NAME IS 'Tên Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT10.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_GL_SEGMENT10_PK ON COMMON_GL_SEGMENT10
(SEGMENT_CODE   ASC);



ALTER TABLE COMMON_GL_SEGMENT10
	ADD CONSTRAINT  COMMON_GL_SEGMENT10_PK PRIMARY KEY (SEGMENT_CODE);



CREATE TABLE COMMON_GL_SEGMENT12
(
	SEGMENT_CODE         VARCHAR2(100) NOT NULL ,
	SEGMENT_NAME         NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_GL_SEGMENT12 IS 'Nguồn';




COMMENT ON COLUMN COMMON_GL_SEGMENT12.SEGMENT_CODE IS 'Mã Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT12.SEGMENT_NAME IS 'Tên Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT12.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_GL_SEGMENT12_PK ON COMMON_GL_SEGMENT12
(SEGMENT_CODE   ASC);



ALTER TABLE COMMON_GL_SEGMENT12
	ADD CONSTRAINT  COMMON_GL_SEGMENT12_PK PRIMARY KEY (SEGMENT_CODE);



CREATE TABLE COMMON_GL_SEGMENT13
(
	SEGMENT_CODE         VARCHAR2(100) NOT NULL ,
	SEGMENT_NAME         NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_GL_SEGMENT13 IS 'DP';




COMMENT ON COLUMN COMMON_GL_SEGMENT13.SEGMENT_CODE IS 'Mã Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT13.SEGMENT_NAME IS 'Tên Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT13.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_GL_SEGMENT13_PK ON COMMON_GL_SEGMENT13
(SEGMENT_CODE   ASC);



ALTER TABLE COMMON_GL_SEGMENT13
	ADD CONSTRAINT  COMMON_GL_SEGMENT13_PK PRIMARY KEY (SEGMENT_CODE);



CREATE TABLE COMMON_GL_SEGMENT2
(
	SEGMENT_CODE         VARCHAR2(100) NOT NULL ,
	SEGMENT_NAME         NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_GL_SEGMENT2 IS 'TKTN';




COMMENT ON COLUMN COMMON_GL_SEGMENT2.SEGMENT_CODE IS 'Mã Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT2.SEGMENT_NAME IS 'Tên Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT2.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_GL_SEGMENT2_PK ON COMMON_GL_SEGMENT2
(SEGMENT_CODE   ASC);



ALTER TABLE COMMON_GL_SEGMENT2
	ADD CONSTRAINT  COMMON_GL_SEGMENT2_PK PRIMARY KEY (SEGMENT_CODE);



CREATE TABLE COMMON_GL_SEGMENT4
(
	SEGMENT_CODE         VARCHAR2(100) NOT NULL ,
	SEGMENT_NAME         NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_GL_SEGMENT4 IS 'NDKT';




COMMENT ON COLUMN COMMON_GL_SEGMENT4.SEGMENT_CODE IS 'Mã Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT4.SEGMENT_NAME IS 'Tên Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT4.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_GL_SEGMENT4_PK ON COMMON_GL_SEGMENT4
(SEGMENT_CODE   ASC);



ALTER TABLE COMMON_GL_SEGMENT4
	ADD CONSTRAINT  COMMON_GL_SEGMENT4_PK PRIMARY KEY (SEGMENT_CODE);



CREATE TABLE COMMON_GL_SEGMENT5
(
	SEGMENT_CODE         VARCHAR2(100) NOT NULL ,
	SEGMENT_NAME         NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_GL_SEGMENT5 IS 'Cấp NS';




COMMENT ON COLUMN COMMON_GL_SEGMENT5.SEGMENT_CODE IS 'Mã Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT5.SEGMENT_NAME IS 'Tên Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT5.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_GL_SEGMENT5_PK ON COMMON_GL_SEGMENT5
(SEGMENT_CODE   ASC);



ALTER TABLE COMMON_GL_SEGMENT5
	ADD CONSTRAINT  COMMON_GL_SEGMENT5_PK PRIMARY KEY (SEGMENT_CODE);



CREATE TABLE COMMON_GL_SEGMENT8
(
	SEGMENT_CODE         VARCHAR2(100) NOT NULL ,
	SEGMENT_NAME         NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_GL_SEGMENT8 IS 'Chương';




COMMENT ON COLUMN COMMON_GL_SEGMENT8.SEGMENT_CODE IS 'Mã Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT8.SEGMENT_NAME IS 'Tên Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT8.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_GL_SEGMENT8_PK ON COMMON_GL_SEGMENT8
(SEGMENT_CODE   ASC);



ALTER TABLE COMMON_GL_SEGMENT8
	ADD CONSTRAINT  COMMON_GL_SEGMENT8_PK PRIMARY KEY (SEGMENT_CODE);



CREATE TABLE COMMON_GL_SEGMENT9
(
	SEGMENT_CODE         VARCHAR2(100) NOT NULL ,
	SEGMENT_NAME         NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_GL_SEGMENT9 IS 'Ngành';




COMMENT ON COLUMN COMMON_GL_SEGMENT9.SEGMENT_CODE IS 'Mã Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT9.SEGMENT_NAME IS 'Tên Segment';




COMMENT ON COLUMN COMMON_GL_SEGMENT9.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX COMMON_GL_SEGMENT9_PK ON COMMON_GL_SEGMENT9
(SEGMENT_CODE   ASC);



ALTER TABLE COMMON_GL_SEGMENT9
	ADD CONSTRAINT  COMMON_GL_SEGMENT9_PK PRIMARY KEY (SEGMENT_CODE);



CREATE TABLE COMMON_INVESTMENT_SOURCE
(
	INVESTMENT_SOURCE_CODE VARCHAR2(100) NOT NULL ,
	INVESTMENT_SOURCE_NAME NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	SEGMENT_CODE         VARCHAR2(100) NOT NULL 
);



COMMENT ON TABLE COMMON_INVESTMENT_SOURCE IS 'Mã nguồn đầu tư';




COMMENT ON COLUMN COMMON_INVESTMENT_SOURCE.INVESTMENT_SOURCE_CODE IS 'Mã nguồn đầu tư';




COMMENT ON COLUMN COMMON_INVESTMENT_SOURCE.INVESTMENT_SOURCE_NAME IS 'Tên nguồn đầu tư';




COMMENT ON COLUMN COMMON_INVESTMENT_SOURCE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN COMMON_INVESTMENT_SOURCE.SEGMENT_CODE IS 'Mã Segment';



CREATE UNIQUE INDEX COMMON_INVESTMENT_SOURCE_PK ON COMMON_INVESTMENT_SOURCE
(INVESTMENT_SOURCE_CODE   ASC,SEGMENT_CODE   ASC);



ALTER TABLE COMMON_INVESTMENT_SOURCE
	ADD CONSTRAINT  COMMON_INVESTMENT_SOURCE_PK PRIMARY KEY (INVESTMENT_SOURCE_CODE,SEGMENT_CODE);



CREATE TABLE COMMON_STATE
(
	STATE_CODE           VARCHAR2(100) NOT NULL ,
	STATE_NAME           NVARCHAR2(500) NULL ,
	STATUS               NUMBER(1) NULL ,
	SUB_SYSTEM           VARCHAR2(100) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE COMMON_STATE IS 'Bảng danh mục trạng thái xử lý';




COMMENT ON COLUMN COMMON_STATE.STATE_CODE IS 'Mã trạng thái xử lý';




COMMENT ON COLUMN COMMON_STATE.STATE_NAME IS 'Tên trạng thái xử lý:
+ Chưa kiểm soát hồ sơ
+ Chờ kiểm soát hồ sơ
+ Từ chối kiểm soát hồ sơ
+ Chờ phê duyệt hồ sơ
+ Từ chối phê duyệt hồ sơ
+ KBNN từ chối hồ sơ
+ Đã hủy kiểm soát hồ sơ
+ Đã hủy phê duyệt hồ sơ';




COMMENT ON COLUMN COMMON_STATE.STATUS IS 'Tình trạng sử dụng: 0-Không sử dụng, 1-Đang sử dụng';




COMMENT ON COLUMN COMMON_STATE.SUB_SYSTEM IS 'Phân hệ sử dụng';




COMMENT ON COLUMN COMMON_STATE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN COMMON_STATE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN COMMON_STATE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN COMMON_STATE.UPDATED_DATE IS 'Ngày cập nhật';




COMMENT ON COLUMN COMMON_STATE.DESCRIPTION IS 'Mô tả trạng thái xử lý';



CREATE UNIQUE INDEX COMMON_STATE_PK ON COMMON_STATE
(STATE_CODE   ASC);



ALTER TABLE COMMON_STATE
	ADD CONSTRAINT  COMMON_STATE_PK PRIMARY KEY (STATE_CODE);



CREATE TABLE COMMON_TREASURY
(
	TREASURY_CODE        VARCHAR2(100) NOT NULL ,
	TREASURY_NAME        NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL 
);



COMMENT ON TABLE COMMON_TREASURY IS 'DMDC - Danh mục Kho bạc Nhà nước';




COMMENT ON COLUMN COMMON_TREASURY.TREASURY_CODE IS 'Mã kho bạc';




COMMENT ON COLUMN COMMON_TREASURY.TREASURY_NAME IS 'Tên kho bạc';




COMMENT ON COLUMN COMMON_TREASURY.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN COMMON_TREASURY.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN COMMON_TREASURY.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN COMMON_TREASURY.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN COMMON_TREASURY.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN COMMON_TREASURY.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX COMMON_TREASURY_PK ON COMMON_TREASURY
(TREASURY_CODE   ASC);



ALTER TABLE COMMON_TREASURY
	ADD CONSTRAINT  COMMON_TREASURY_PK PRIMARY KEY (TREASURY_CODE);



CREATE TABLE EXP_ACCOUNTING_PERIOD
(
	PERIOD_ID            NUMBER(18) NOT NULL ,
	PERIOD_NAME          NVARCHAR2(500) NULL ,
	PERIOD_TYPE          VARCHAR2(20) NULL ,
	FROM_DATE            DATE NULL ,
	TO_DATE              DATE NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE EXP_ACCOUNTING_PERIOD IS 'Bảng thông tin kỳ kế toán để kiểm tra khóa sổ';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.PERIOD_ID IS 'Mã ID tự sinh từ sequence';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.PERIOD_NAME IS 'Tên kỳ kế toán';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.PERIOD_TYPE IS 'Loại kỳ kế toán (Tháng, Quý, Năm)';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.FROM_DATE IS 'Ngày bắt đầu';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.TO_DATE IS 'Ngày kết thúc';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.STATUS IS 'Trạng thái: 0-Khóa, 1-Mở';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.UPDATED_DATE IS 'Ngày cập nhật';




COMMENT ON COLUMN EXP_ACCOUNTING_PERIOD.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX EXP_ACCOUNTING_PERIOD_PK ON EXP_ACCOUNTING_PERIOD
(PERIOD_ID   ASC);



ALTER TABLE EXP_ACCOUNTING_PERIOD
	ADD CONSTRAINT  EXP_ACCOUNTING_PERIOD_PK PRIMARY KEY (PERIOD_ID);



CREATE TABLE EXP_APPROVAL_LOG
(
	ACTION_USER          VARCHAR2(100) NULL ,
	ACTION_DATE          DATE NULL ,
	REASON               NVARCHAR2(2000) NULL ,
	APPROVAL_LOG_ID      RAW(16) NOT NULL ,
	ACTION_ROLE          VARCHAR2(100) NULL ,
	STATE_CODE           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	DOSSIER_ID           RAW(16) NOT NULL ,
	PARENT_ID            RAW(16) NULL 
);



COMMENT ON TABLE EXP_APPROVAL_LOG IS 'Bảng thông tin luồng phê duyệt của hồ sơ';




COMMENT ON COLUMN EXP_APPROVAL_LOG.ACTION_USER IS 'Người thực hiện';




COMMENT ON COLUMN EXP_APPROVAL_LOG.ACTION_DATE IS 'Thời điểm thực hiện';




COMMENT ON COLUMN EXP_APPROVAL_LOG.REASON IS 'Lý do';




COMMENT ON COLUMN EXP_APPROVAL_LOG.APPROVAL_LOG_ID IS 'Mã ID tự sinh từ sequence';




COMMENT ON COLUMN EXP_APPROVAL_LOG.ACTION_ROLE IS 'Vai trò thực hiện (Maker, Checker, Approver)';




COMMENT ON COLUMN EXP_APPROVAL_LOG.STATE_CODE IS 'Trạng thái';




COMMENT ON COLUMN EXP_APPROVAL_LOG.CREATED_DATE IS 'Thời điểm tạo bản ghi';




COMMENT ON COLUMN EXP_APPROVAL_LOG.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_APPROVAL_LOG.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_APPROVAL_LOG.UPDATED_DATE IS 'Thời điểm cập nhật';




COMMENT ON COLUMN EXP_APPROVAL_LOG.DOSSIER_ID IS 'ID hồ sơ tự sinh từ sequence';




COMMENT ON COLUMN EXP_APPROVAL_LOG.PARENT_ID IS 'ID tham chiếu đến bản ghi APPROVAL_LOG_ID trước';



CREATE UNIQUE INDEX EXP_APPROVAL_LOG_PK ON EXP_APPROVAL_LOG
(APPROVAL_LOG_ID   ASC);



ALTER TABLE EXP_APPROVAL_LOG
	ADD CONSTRAINT  EXP_APPROVAL_LOG_PK PRIMARY KEY (APPROVAL_LOG_ID);



CREATE TABLE EXP_ARCHIVE
(
	ARCHIVE_ID           RAW(16) NOT NULL ,
	DOSSIER_ID           RAW(16) NOT NULL ,
	FILE_NAME            VARCHAR2(200) NULL ,
	FILE_PATH            VARCHAR2(2000) NULL ,
	ARCHIVE_TYPE         VARCHAR2(20) NULL ,
	ARCHIVE_DATE         DATE NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_DATE         DATE NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE EXP_ARCHIVE IS 'Bảng thông tin lưu trữ điện tử';




COMMENT ON COLUMN EXP_ARCHIVE.ARCHIVE_ID IS 'Mã ID bản ghi tự sinh từ sequence';




COMMENT ON COLUMN EXP_ARCHIVE.DOSSIER_ID IS 'Mă ID hồ sơ tham chiếu';




COMMENT ON COLUMN EXP_ARCHIVE.FILE_NAME IS 'Tên file';




COMMENT ON COLUMN EXP_ARCHIVE.FILE_PATH IS 'Đường dẫn file';




COMMENT ON COLUMN EXP_ARCHIVE.ARCHIVE_TYPE IS 'Loại thông tin lưu trữ';




COMMENT ON COLUMN EXP_ARCHIVE.ARCHIVE_DATE IS 'Ngày lưu trữ';




COMMENT ON COLUMN EXP_ARCHIVE.CREATED_DATE IS 'Thời gian tạo bản ghi';




COMMENT ON COLUMN EXP_ARCHIVE.UPDATED_DATE IS 'Thời gian cập nhật';




COMMENT ON COLUMN EXP_ARCHIVE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_ARCHIVE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_ARCHIVE.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX EXP_ARCHIVE_PK ON EXP_ARCHIVE
(ARCHIVE_ID   ASC);



ALTER TABLE EXP_ARCHIVE
	ADD CONSTRAINT  EXP_ARCHIVE_PK PRIMARY KEY (ARCHIVE_ID);



CREATE TABLE EXP_CAPITAL_PLAN_TYPE
(
	CAPITAL_PLAN_TYPE_CODE VARCHAR2(100) NOT NULL ,
	CAPITAL_PLAN_TYPE_NAME NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL 
);



COMMENT ON TABLE EXP_CAPITAL_PLAN_TYPE IS 'Danh mục Loại kế hoạch vốn';




COMMENT ON COLUMN EXP_CAPITAL_PLAN_TYPE.CAPITAL_PLAN_TYPE_CODE IS 'Mã loại kế hoạch vốn';




COMMENT ON COLUMN EXP_CAPITAL_PLAN_TYPE.CAPITAL_PLAN_TYPE_NAME IS 'Tên loại kế hoạch vốn';




COMMENT ON COLUMN EXP_CAPITAL_PLAN_TYPE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_CAPITAL_PLAN_TYPE.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_CAPITAL_PLAN_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_CAPITAL_PLAN_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_CAPITAL_PLAN_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_CAPITAL_PLAN_TYPE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_CAPITAL_PLAN_TYPE_PK ON EXP_CAPITAL_PLAN_TYPE
(CAPITAL_PLAN_TYPE_CODE   ASC);



ALTER TABLE EXP_CAPITAL_PLAN_TYPE
	ADD CONSTRAINT  EXP_CAPITAL_PLAN_TYPE_PK PRIMARY KEY (CAPITAL_PLAN_TYPE_CODE);



CREATE TABLE EXP_CAPITAL_YEAR
(
	CAPITAL_YEAR         NUMBER(4) NOT NULL 
);



COMMENT ON TABLE EXP_CAPITAL_YEAR IS 'Năm kế hoạch';




COMMENT ON COLUMN EXP_CAPITAL_YEAR.CAPITAL_YEAR IS 'Năm kế hoạch';



CREATE UNIQUE INDEX EXP_CAPITAL_YEAR_PK ON EXP_CAPITAL_YEAR
(CAPITAL_YEAR   ASC);



ALTER TABLE EXP_CAPITAL_YEAR
	ADD CONSTRAINT  EXP_CAPITAL_YEAR_PK PRIMARY KEY (CAPITAL_YEAR);



CREATE TABLE EXP_CURRENCY_TYPE
(
	CURRENCY_TYPE_CODE   VARCHAR2(100) NOT NULL ,
	CURRENCY_TYPE_NAME   NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL 
);



COMMENT ON TABLE EXP_CURRENCY_TYPE IS 'Danh mục Loại tiền';




COMMENT ON COLUMN EXP_CURRENCY_TYPE.CURRENCY_TYPE_CODE IS 'Mã loại tiền';




COMMENT ON COLUMN EXP_CURRENCY_TYPE.CURRENCY_TYPE_NAME IS 'Tên loại tiền';




COMMENT ON COLUMN EXP_CURRENCY_TYPE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_CURRENCY_TYPE.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_CURRENCY_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_CURRENCY_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_CURRENCY_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_CURRENCY_TYPE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_CURRENCY_TYPE_PK ON EXP_CURRENCY_TYPE
(CURRENCY_TYPE_CODE   ASC);



ALTER TABLE EXP_CURRENCY_TYPE
	ADD CONSTRAINT  EXP_CURRENCY_TYPE_PK PRIMARY KEY (CURRENCY_TYPE_CODE);



CREATE TABLE EXP_DATA_SOURCE
(
	DATA_SOURCE_CODE     VARCHAR2(100) NOT NULL ,
	DATA_SOURCE_NAME     NVARCHAR2(500) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE EXP_DATA_SOURCE IS 'Danh mục nguồn gốc hồ sơ (DVC, Thủ công, Chuyển đổi)';




COMMENT ON COLUMN EXP_DATA_SOURCE.DATA_SOURCE_CODE IS 'Mã nguồn gốc hồ sơ';




COMMENT ON COLUMN EXP_DATA_SOURCE.DATA_SOURCE_NAME IS 'Nguồn gốc hồ sơ (DVC, Thủ công, Chuyển đổi)';




COMMENT ON COLUMN EXP_DATA_SOURCE.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_DATA_SOURCE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DATA_SOURCE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DATA_SOURCE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DATA_SOURCE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DATA_SOURCE_PK ON EXP_DATA_SOURCE
(DATA_SOURCE_CODE   ASC);



ALTER TABLE EXP_DATA_SOURCE
	ADD CONSTRAINT  EXP_DATA_SOURCE_PK PRIMARY KEY (DATA_SOURCE_CODE);



CREATE TABLE EXP_DIGITAL_SIGNED
(
	SIGNED_CONTENT       VARCHAR2(2000) NULL ,
	SIGNATURE            VARCHAR2(4000 BYTE) NULL ,
	SIGNED_DATE          DATE NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	SIGNED_USER          VARCHAR2(100) NULL ,
	SIGNED_ROLE          VARCHAR2(100) NULL ,
	APPROVAL_LOG_ID      RAW(16) NOT NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	SIGNATURE_STATUS     NUMBER(1) NULL ,
	CERT                 CLOB NULL 
);



COMMENT ON TABLE EXP_DIGITAL_SIGNED IS 'Bảng lưu thông tin ký số của hồ sơ';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNED_CONTENT IS 'Thông tin ký số
Định dạng JSON: {documentHash="abc",signerHash="def" algorithm="SHA256"}';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNATURE IS 'Thông tin chữ ký số';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNED_DATE IS 'Ngày ký';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.CREATED_BY IS 'Người tạo bản ghi';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNED_USER IS 'Người ký';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNED_ROLE IS 'Vai trò ký';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.APPROVAL_LOG_ID IS 'Mã ID tham chiếu bước phê duyệt';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.CREATED_DATE IS 'Thời gian tạo';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.UPDATED_DATE IS 'Thời gian cập nhật';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.SIGNATURE_STATUS IS 'Trạng thái của chữ ký số: 0-Hết hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_DIGITAL_SIGNED.CERT IS 'Thông tin chứng thực ký số';



CREATE UNIQUE INDEX EXP_DIGITAL_SIGNED_PK ON EXP_DIGITAL_SIGNED
(APPROVAL_LOG_ID   ASC);



ALTER TABLE EXP_DIGITAL_SIGNED
	ADD CONSTRAINT  EXP_DIGITAL_SIGNED_PK PRIMARY KEY (APPROVAL_LOG_ID);



CREATE TABLE EXP_DOCUMENT
(
	DOCUMENT_ID          RAW(16) NOT NULL ,
	DOSSIER_ID           RAW(16) NOT NULL ,
	DOMESTIC_ACCOUNT     VARCHAR2(200) NULL ,
	DOMESTIC_BANK        NVARCHAR2(500) NULL ,
	FOREIGN_ACCOUNT      VARCHAR2(200) NULL ,
	FOREIGN_BANK         NVARCHAR2(500) NULL ,
	DOCUMENT_NUMBER      VARCHAR2(200) NULL ,
	DOCUMENT_DATE        DATE NULL ,
	ACCOUNTING_DATE      DATE NULL ,
	DOCUMENT_TEMPLATE_ID NUMBER(18) NOT NULL ,
	FISCAL_YEAR          NUMBER(4) NULL ,
	PAYMENT_REQUEST_NO   VARCHAR2(200) NULL ,
	PAYMENT_REQUEST_DATE DATE NULL ,
	TREASURY_CODE        VARCHAR2(100) NOT NULL ,
	PAYING_TREASURY_CODE VARCHAR2(100) NULL ,
	PAYMENT_TYPE_CODE    VARCHAR2(100) NOT NULL ,
	GUARANTEE_REVOKED_DATE DATE NULL ,
	COMPLETED_WORKLOAD_NO NUMBER(18) NULL ,
	COMPLETED_WORKLOAD_DATE DATE NULL ,
	GUARANTEE_NO         VARCHAR2(100) NULL ,
	GUARANTEE_AMOUNT     NUMBER(18) NULL ,
	GUARANTEE_REMAIN_AMOUNT NUMBER(18) NULL ,
	GUARANTEE_EXPIRY_DATE DATE NULL ,
	CUMULATIVE_WORKLOAD_PAYMENT NUMBER(18) NULL ,
	CUMULATIVE_PAID_CAPITAL NUMBER(18) NULL ,
	ADVANCE_PAYMENT_AMOUNT NUMBER(18) NULL ,
	DOCUMENT_TYPE_CODE   VARCHAR2(100) NULL ,
	CAPITAL_PLAN_TYPE_CODE VARCHAR2(100) NOT NULL ,
	GUARANTEE_ID         NUMBER(18) NOT NULL ,
	PROJECT_ITEM_CODE    VARCHAR2(100) NOT NULL ,
	CURRENCY_TYPE_CODE   VARCHAR2(100) NOT NULL ,
	EXCHANGE_RATE_TYPE_CODE VARCHAR2(100) NOT NULL ,
	EXCHANGE_RATE_DATE   DATE NULL ,
	EXCHANGE_RATE        NUMBER(18,2) NULL ,
	PROJECT_ITEM_NAME    NVARCHAR2(500) NULL 
);



COMMENT ON TABLE EXP_DOCUMENT IS 'Bảng thông tin chứng từ của hồ sơ';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_ID IS 'ID chứng từ tự sinh từ sequence';




COMMENT ON COLUMN EXP_DOCUMENT.DOSSIER_ID IS 'Mã ID tham chiếu hồ sơ';




COMMENT ON COLUMN EXP_DOCUMENT.DOMESTIC_ACCOUNT IS 'Số tài khoản của chủ đầu tư - Vốn trong nước';




COMMENT ON COLUMN EXP_DOCUMENT.DOMESTIC_BANK IS 'Nơi mở số tài khoản của chủ đầu tư - Vốn trong nước';




COMMENT ON COLUMN EXP_DOCUMENT.FOREIGN_ACCOUNT IS 'Số tài khoản của chủ đầu tư - Vốn ngoài nước';




COMMENT ON COLUMN EXP_DOCUMENT.FOREIGN_BANK IS 'Nơi mở số tài khoản của chủ đầu tư - Vốn ngoài nước';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_NUMBER IS 'Số chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_DATE IS 'Ngày chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT.ACCOUNTING_DATE IS 'Ngày hạch toán';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_TEMPLATE_ID IS 'Mã ID tự sinh từ sequence';




COMMENT ON COLUMN EXP_DOCUMENT.FISCAL_YEAR IS 'Niên độ';




COMMENT ON COLUMN EXP_DOCUMENT.PAYMENT_REQUEST_NO IS 'Số hiệu giấy đề nghị thanh toán';




COMMENT ON COLUMN EXP_DOCUMENT.PAYMENT_REQUEST_DATE IS 'Ngày đề nghị thanh toán';




COMMENT ON COLUMN EXP_DOCUMENT.TREASURY_CODE IS 'Mã kho bạc';




COMMENT ON COLUMN EXP_DOCUMENT.PAYING_TREASURY_CODE IS 'Mã kho bạc thanh toán';




COMMENT ON COLUMN EXP_DOCUMENT.PAYMENT_TYPE_CODE IS 'Mã loại thanh toán (Tạm ứng, thanh toán)';




COMMENT ON COLUMN EXP_DOCUMENT.GUARANTEE_REVOKED_DATE IS 'Ngày thu hồi bảo lãnh';




COMMENT ON COLUMN EXP_DOCUMENT.COMPLETED_WORKLOAD_NO IS 'Số bảng kê KLHT';




COMMENT ON COLUMN EXP_DOCUMENT.COMPLETED_WORKLOAD_DATE IS 'Ngày bảng kê KLHT';




COMMENT ON COLUMN EXP_DOCUMENT.GUARANTEE_NO IS 'Số bảo lãnh';




COMMENT ON COLUMN EXP_DOCUMENT.GUARANTEE_AMOUNT IS 'Số tiền bảo lãnh';




COMMENT ON COLUMN EXP_DOCUMENT.GUARANTEE_REMAIN_AMOUNT IS 'Số tiền bảo lãnh còn lại';




COMMENT ON COLUMN EXP_DOCUMENT.GUARANTEE_EXPIRY_DATE IS 'Ngày hết hạn bảo lãnh';




COMMENT ON COLUMN EXP_DOCUMENT.CUMULATIVE_WORKLOAD_PAYMENT IS 'Lũy kế giá trị khối lượng đề nghị thanh toán';




COMMENT ON COLUMN EXP_DOCUMENT.CUMULATIVE_PAID_CAPITAL IS 'Lũy kế số vốn đã thanh toán từ khởi công đến cuối kỳ trước';




COMMENT ON COLUMN EXP_DOCUMENT.ADVANCE_PAYMENT_AMOUNT IS 'Số dư tạm ứng';




COMMENT ON COLUMN EXP_DOCUMENT.DOCUMENT_TYPE_CODE IS 'Mã loại chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT.CAPITAL_PLAN_TYPE_CODE IS 'Mã loại kế hoạch vốn';




COMMENT ON COLUMN EXP_DOCUMENT.GUARANTEE_ID IS 'Mã ID tham chiếu bảo lãnh';




COMMENT ON COLUMN EXP_DOCUMENT.PROJECT_ITEM_CODE IS 'Mã hạng mục';




COMMENT ON COLUMN EXP_DOCUMENT.CURRENCY_TYPE_CODE IS 'Mã loại tiền';




COMMENT ON COLUMN EXP_DOCUMENT.EXCHANGE_RATE_TYPE_CODE IS 'Mã loại tỷ giá';




COMMENT ON COLUMN EXP_DOCUMENT.EXCHANGE_RATE_DATE IS 'Ngày tỷ giá';




COMMENT ON COLUMN EXP_DOCUMENT.EXCHANGE_RATE IS 'Tỷ giá';




COMMENT ON COLUMN EXP_DOCUMENT.PROJECT_ITEM_NAME IS 'Tên hạng mục';



CREATE UNIQUE INDEX EXP_DOCUMENT_PK ON EXP_DOCUMENT
(DOCUMENT_ID   ASC);



ALTER TABLE EXP_DOCUMENT
	ADD CONSTRAINT  EXP_DOCUMENT_PK PRIMARY KEY (DOCUMENT_ID);



CREATE TABLE EXP_DOCUMENT_LINE
(
	DOCUMENT_ID          RAW(16) NOT NULL ,
	DOCUMENT_LINE_ID     RAW(16) NOT NULL ,
	CAPITAL_YEAR         NUMBER(4) NOT NULL ,
	EXTENDED             NUMBER(1) NULL ,
	INVESTMENT_SOURCE_CODE VARCHAR2(100) NOT NULL ,
	ALLOCATION_CRITERIA_CODE VARCHAR2(100) NOT NULL ,
	PAYMENT_REQUEST_AMOUNT NUMBER(18) NULL ,
	PAYMENT_REQUEST_AMOUNT_VND NUMBER(18) NULL ,
	APPROVED_AMOUNT      NUMBER(18) NULL ,
	APPROVED_AMOUNT_VND  NUMBER(18) NULL ,
	ADVANCE_DEDUCTION_AMOUNT NUMBER(18) NULL ,
	ADVANCE_DEDUCTION_AMOUNT_VND NUMBER(18) NULL ,
	WARRANTY_AMOUNT      NUMBER(18) NULL ,
	WARRANTY_AMOUNT_VND  NUMBER(18) NULL ,
	PENDING_SETTLEMENT_AMOUNT NUMBER(18) NULL ,
	PENDING_SETTLEMENT_AMOUNT_VND NUMBER(18) NULL ,
	VALUE_ADDED_TAX_AMOUNT NUMBER(18) NULL ,
	TRANSFER_BENEFICIARY_AMOUNT NUMBER(18) NULL ,
	TRANSFER_BENEFICIARY_AMOUNT_VN NUMBER(18) NULL ,
	BENEFICIARY_NAME     NVARCHAR2(500) NULL ,
	BENEFICIARY_ACCOUNT  VARCHAR2(200) NULL ,
	BENEFICIARY_BANK_NAME NVARCHAR2(500) NULL ,
	GL_SEGMENT2          VARCHAR2(100) NOT NULL ,
	GL_SEGMENT4          VARCHAR2(100) NOT NULL ,
	GL_SEGMENT5          VARCHAR2(100) NOT NULL ,
	GL_SEGMENT8          VARCHAR2(100) NOT NULL ,
	GL_SEGMENT9          VARCHAR2(100) NOT NULL ,
	GL_SEGMENT10         VARCHAR2(100) NOT NULL ,
	GL_SEGMENT12         VARCHAR2(100) NOT NULL ,
	GL_SEGMENT13         VARCHAR2(100) NOT NULL ,
	BENEFICIARY_BANK_CODE VARCHAR2(100) NOT NULL 
);




COMMENT ON COLUMN EXP_DOCUMENT_LINE.DOCUMENT_ID IS 'ID tham chiếu chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.DOCUMENT_LINE_ID IS 'Mã ID dòng chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.CAPITAL_YEAR IS 'Năm kế hoạch';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.EXTENDED IS 'Kéo dài: 1-Kéo dài, 2-Không kéo dài';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.INVESTMENT_SOURCE_CODE IS 'Mã nguồn đầu tư';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.ALLOCATION_CRITERIA_CODE IS 'Tiêu thức phân bổ';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.PAYMENT_REQUEST_AMOUNT IS 'Số ĐNTT NT';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.PAYMENT_REQUEST_AMOUNT_VND IS 'Số ĐNTT VND';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.APPROVED_AMOUNT IS 'Số KBNN duyệt NT';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.APPROVED_AMOUNT_VND IS 'Số KBNN duyệt VND';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.ADVANCE_DEDUCTION_AMOUNT IS 'Số thu hồi tạm ứng NT';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.ADVANCE_DEDUCTION_AMOUNT_VND IS 'Số thu hồi tạm ứng VND';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.WARRANTY_AMOUNT IS 'Số chuyển bảo hành NT';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.WARRANTY_AMOUNT_VND IS 'Số chuyển bảo hành VND';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.PENDING_SETTLEMENT_AMOUNT IS 'Số tạm giữ chờ quyết toán NT';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.PENDING_SETTLEMENT_AMOUNT_VND IS 'Số tạm giữ chờ quyết toán VND';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.VALUE_ADDED_TAX_AMOUNT IS 'Thuế giá trị gia tăng';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.TRANSFER_BENEFICIARY_AMOUNT IS 'Số chuyển đơn vị thụ hưởng NT';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.TRANSFER_BENEFICIARY_AMOUNT_VN IS 'Số chuyển đơn vị thụ hưởng VND';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.BENEFICIARY_NAME IS 'Tên đơn vị thụ hưởng';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.BENEFICIARY_ACCOUNT IS 'Số tài khoản đơn vị thụ hưởng';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.BENEFICIARY_BANK_NAME IS 'Tên ngân hàng đơn vị thụ hưởng';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.GL_SEGMENT2 IS 'TKTN';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.GL_SEGMENT4 IS 'NDKT';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.GL_SEGMENT5 IS 'Cấp NS';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.GL_SEGMENT8 IS 'Chương';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.GL_SEGMENT9 IS 'Ngành';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.GL_SEGMENT10 IS 'CTMT';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.GL_SEGMENT12 IS 'Nguồn';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.GL_SEGMENT13 IS 'DP';




COMMENT ON COLUMN EXP_DOCUMENT_LINE.BENEFICIARY_BANK_CODE IS 'Mã ngân hàng đơn vị thụ hưởng';



CREATE UNIQUE INDEX EXP_DOCUMENT_LINE_PK ON EXP_DOCUMENT_LINE
(DOCUMENT_LINE_ID   ASC);



ALTER TABLE EXP_DOCUMENT_LINE
	ADD CONSTRAINT  EXP_DOCUMENT_LINE_PK PRIMARY KEY (DOCUMENT_LINE_ID);



CREATE TABLE EXP_DOCUMENT_TEMPLATE
(
	DOCUMENT_TEMPLATE_ID NUMBER(18) NOT NULL ,
	TEMPLATE_CODE        VARCHAR2(100) NULL ,
	TEMPLATE_NAME        NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	DOCUMENT_TYPE_CODE   VARCHAR2(100) NOT NULL 
);



COMMENT ON TABLE EXP_DOCUMENT_TEMPLATE IS 'Danh mục các mẫu chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.DOCUMENT_TEMPLATE_ID IS 'Mã ID tự sinh từ sequence';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.TEMPLATE_CODE IS 'Mã mẫu chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.TEMPLATE_NAME IS 'Tên mẫu chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.STATUS IS 'Trạng thái: 0-Không sử dụng, 1-Đang sử dụng';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.UPDATED_DATE IS 'Ngày cập nhật';




COMMENT ON COLUMN EXP_DOCUMENT_TEMPLATE.DOCUMENT_TYPE_CODE IS 'Mã loại chứng từ';



CREATE UNIQUE INDEX EXP_DOCUMENT_TEMPLATE_PK ON EXP_DOCUMENT_TEMPLATE
(DOCUMENT_TEMPLATE_ID   ASC);



ALTER TABLE EXP_DOCUMENT_TEMPLATE
	ADD CONSTRAINT  EXP_DOCUMENT_TEMPLATE_PK PRIMARY KEY (DOCUMENT_TEMPLATE_ID);



CREATE TABLE EXP_DOCUMENT_TYPE
(
	DOCUMENT_TYPE_CODE   VARCHAR2(100) NOT NULL ,
	DOCUMENT_TYPE_NAME   NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL 
);



COMMENT ON TABLE EXP_DOCUMENT_TYPE IS 'Danh mục Loại chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.DOCUMENT_TYPE_CODE IS 'Mã loại chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.DOCUMENT_TYPE_NAME IS 'Tên loại chứng từ';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOCUMENT_TYPE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_DOCUMENT_TYPE_PK ON EXP_DOCUMENT_TYPE
(DOCUMENT_TYPE_CODE   ASC);



ALTER TABLE EXP_DOCUMENT_TYPE
	ADD CONSTRAINT  EXP_DOCUMENT_TYPE_PK PRIMARY KEY (DOCUMENT_TYPE_CODE);



CREATE TABLE EXP_DOSSIER
(
	DOSSIER_ID           RAW(16) NOT NULL ,
	DOSSIER_CODE         VARCHAR2(100) NULL ,
	SEND_DATE            DATE NULL ,
	RECEIVE_DATE         DATE NULL ,
	STATE_CODE           VARCHAR2(100) NOT NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	DATA_SOURCE_CODE     VARCHAR2(100) NOT NULL ,
	CREATED_DATE         DATE NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	SLA                  DATE NULL ,
	COMPLETED_DATE       DATE NULL ,
	PROJECT_SPECIFIC_CODE VARCHAR2(100) NULL ,
	PROJECT_CODE         VARCHAR2(100) NOT NULL ,
	PROJECT_SPECIFIC_NAME NVARCHAR2(500) NULL ,
	INVESTOR_NAME        NVARCHAR2(500) NULL ,
	PROJECT_NAME         NVARCHAR2(500) NULL ,
	ASSIGN_USER          VARCHAR2(100) NULL ,
	WORKFLOW_ID          NUMBER(18) NOT NULL ,
	TREASURY_CODE        VARCHAR2(100) NOT NULL ,
	HASH_INFO            VARCHAR2(2000) NULL ,
	PROJECT_MANAGEMENT_NAME NVARCHAR2(500) NULL ,
	DOSSIER_VERSION      NUMBER(3) NULL ,
	STATUS               NUMBER(1) NULL 
);



COMMENT ON TABLE EXP_DOSSIER IS 'Bảng dữ liệu thông tin hồ sơ chi';




COMMENT ON COLUMN EXP_DOSSIER.DOSSIER_ID IS 'ID hồ sơ tự sinh từ sequence';




COMMENT ON COLUMN EXP_DOSSIER.DOSSIER_CODE IS 'Mã hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.SEND_DATE IS 'Ngày gửi hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.RECEIVE_DATE IS 'Ngày nhận hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.STATE_CODE IS 'Trạng thái hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.UPDATED_BY IS 'Người cập nhật lần cuối';




COMMENT ON COLUMN EXP_DOSSIER.UPDATED_DATE IS 'Thời gian cập nhật lần cuối';




COMMENT ON COLUMN EXP_DOSSIER.DATA_SOURCE_CODE IS 'ID tham chiếu đến danh mục nguồn gốc hồ sơ (DVC, Thủ công, Chuyển đổi)';




COMMENT ON COLUMN EXP_DOSSIER.CREATED_DATE IS 'Thời gian tạo';




COMMENT ON COLUMN EXP_DOSSIER.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOSSIER.SLA IS 'Thời hạn xử lý theo SLA';




COMMENT ON COLUMN EXP_DOSSIER.COMPLETED_DATE IS 'Ngày hoàn thành hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_SPECIFIC_CODE IS 'Mã dự án đặc thù';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_CODE IS 'Mã dự án';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_SPECIFIC_NAME IS 'Tên dự án đặc thù';




COMMENT ON COLUMN EXP_DOSSIER.INVESTOR_NAME IS 'Tên chủ đầu tư';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_NAME IS 'Tên dự án';




COMMENT ON COLUMN EXP_DOSSIER.ASSIGN_USER IS 'Người đang xử lý hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.WORKFLOW_ID IS 'Mã ID tham chiếu luồng xử lý';




COMMENT ON COLUMN EXP_DOSSIER.TREASURY_CODE IS 'Mã kho bạc';




COMMENT ON COLUMN EXP_DOSSIER.HASH_INFO IS 'Thông tin hash của hồ sơ (bao gồm tất cả chứng từ bên trong) khi gửi phê duyệt.
Định dạng JSON: {documentHash="abc", algorithm="SHA256"}';




COMMENT ON COLUMN EXP_DOSSIER.PROJECT_MANAGEMENT_NAME IS 'Tên Ban QLDA';




COMMENT ON COLUMN EXP_DOSSIER.DOSSIER_VERSION IS 'Phiên bản hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER.STATUS IS 'Hiệu lực hồ sơ: 0-Hết hiệu lực, 1-Đang hiệu lực';



CREATE UNIQUE INDEX EXP_DOSSIER_PK ON EXP_DOSSIER
(DOSSIER_ID   ASC);



ALTER TABLE EXP_DOSSIER
	ADD CONSTRAINT  EXP_DOSSIER_PK PRIMARY KEY (DOSSIER_ID);



CREATE TABLE EXP_DOSSIER_SLA
(
	DOSSIER_ID           RAW(16) NOT NULL ,
	DOSSIER_SLA_ID       RAW(16) NOT NULL ,
	ACTION_ROLE          VARCHAR2(100) NULL ,
	ACTION_USER          VARCHAR2(200) NULL ,
	SLA                  DATE NULL ,
	IS_NOTIFY            NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL 
);




COMMENT ON COLUMN EXP_DOSSIER_SLA.DOSSIER_ID IS 'ID tham chiếu hồ sơ';




COMMENT ON COLUMN EXP_DOSSIER_SLA.DOSSIER_SLA_ID IS 'Khóa chính là UUID';




COMMENT ON COLUMN EXP_DOSSIER_SLA.ACTION_ROLE IS 'Vai trò';




COMMENT ON COLUMN EXP_DOSSIER_SLA.ACTION_USER IS 'Người thực hiện';




COMMENT ON COLUMN EXP_DOSSIER_SLA.SLA IS 'Thời gian xử lý theo SLA';




COMMENT ON COLUMN EXP_DOSSIER_SLA.IS_NOTIFY IS 'Trạng thái gửi cảnh báo: 0-Chưa gửi, 1-Đã gửi';




COMMENT ON COLUMN EXP_DOSSIER_SLA.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_DOSSIER_SLA.CREATED_DATE IS 'Thời điểm tạo';




COMMENT ON COLUMN EXP_DOSSIER_SLA.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_DOSSIER_SLA.UPDATED_DATE IS 'Thời điểm cập nhật';



CREATE UNIQUE INDEX EXP_DOSSIER_SLA_PK ON EXP_DOSSIER_SLA
(DOSSIER_SLA_ID   ASC);



ALTER TABLE EXP_DOSSIER_SLA
	ADD CONSTRAINT  EXP_DOSSIER_SLA_PK PRIMARY KEY (DOSSIER_SLA_ID);



CREATE TABLE EXP_EXCHANGE_RATE
(
	CURRENCY_TYPE_CODE   VARCHAR2(100) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	EXCHANGE_RATE        NUMBER(18,2) NULL ,
	FROM_DATE            DATE NULL ,
	TO_DATE              DATE NULL ,
	EXCHANGE_RATE_ID     NUMBER(18) NOT NULL 
);



COMMENT ON TABLE EXP_EXCHANGE_RATE IS 'Bảng thông tin tỷ giá theo ngày';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.CURRENCY_TYPE_CODE IS 'Mã loại tiền';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.UPDATED_DATE IS 'Ngày cập nhật';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.EXCHANGE_RATE IS 'Tỷ giá';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.FROM_DATE IS 'Ngày bắt đầu';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.TO_DATE IS 'Ngày kết thúc';




COMMENT ON COLUMN EXP_EXCHANGE_RATE.EXCHANGE_RATE_ID IS 'Mã ID tự sinh từ sequence';



CREATE UNIQUE INDEX EXP_EXCHANGE_RATE_PK ON EXP_EXCHANGE_RATE
(EXCHANGE_RATE_ID   ASC);



ALTER TABLE EXP_EXCHANGE_RATE
	ADD CONSTRAINT  EXP_EXCHANGE_RATE_PK PRIMARY KEY (EXCHANGE_RATE_ID);



CREATE TABLE EXP_EXCHANGE_RATE_TYPE
(
	EXCHANGE_RATE_TYPE_CODE VARCHAR2(100) NOT NULL ,
	EXCHANGE_RATE_TYPE_NAME NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL 
);



COMMENT ON TABLE EXP_EXCHANGE_RATE_TYPE IS 'Danh mục Loại tỷ giá';




COMMENT ON COLUMN EXP_EXCHANGE_RATE_TYPE.EXCHANGE_RATE_TYPE_CODE IS 'Mã loại tỷ giá';




COMMENT ON COLUMN EXP_EXCHANGE_RATE_TYPE.EXCHANGE_RATE_TYPE_NAME IS 'Tên loại tỷ giá (Tỷ giá công ty, Tỷ giá NSD)';




COMMENT ON COLUMN EXP_EXCHANGE_RATE_TYPE.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_EXCHANGE_RATE_TYPE.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_EXCHANGE_RATE_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_EXCHANGE_RATE_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_EXCHANGE_RATE_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_EXCHANGE_RATE_TYPE.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_EXCHANGE_RATE_TYPE_PK ON EXP_EXCHANGE_RATE_TYPE
(EXCHANGE_RATE_TYPE_CODE   ASC);



ALTER TABLE EXP_EXCHANGE_RATE_TYPE
	ADD CONSTRAINT  EXP_EXCHANGE_RATE_TYPE_PK PRIMARY KEY (EXCHANGE_RATE_TYPE_CODE);



CREATE TABLE EXP_GUARANTEE
(
	GUARANTEE_ID         NUMBER(18) NOT NULL ,
	GUARANTEE_AMOUNT     NUMBER(18) NULL ,
	GUARANTEE_REMAINING_AMOUNT NUMBER(18) NULL ,
	GUARANTEE_NO         VARCHAR2(100) NULL ,
	GUARANTEE_EXPIRY_DATE DATE NULL 
);




COMMENT ON COLUMN EXP_GUARANTEE.GUARANTEE_ID IS 'Mã ID tự sinh từ sequence';




COMMENT ON COLUMN EXP_GUARANTEE.GUARANTEE_AMOUNT IS 'Số tiền bảo lãnh';




COMMENT ON COLUMN EXP_GUARANTEE.GUARANTEE_REMAINING_AMOUNT IS 'Số tiền bảo lãnh còn lại';




COMMENT ON COLUMN EXP_GUARANTEE.GUARANTEE_NO IS 'Số bảo lãnh';



CREATE UNIQUE INDEX EXP_GUARANTEE_PK ON EXP_GUARANTEE
(GUARANTEE_ID   ASC);



ALTER TABLE EXP_GUARANTEE
	ADD CONSTRAINT  EXP_GUARANTEE_PK PRIMARY KEY (GUARANTEE_ID);



CREATE TABLE EXP_INVESTOR
(
	INVESTOR_CODE        VARCHAR2(100) NOT NULL ,
	INVESTOR_NAME        NVARCHAR2(500) NULL ,
	DOMESTIC_ACCOUNT     VARCHAR2(100) NULL ,
	FOREIGN_ACCOUNT      VARCHAR2(100) NULL ,
	FOREIGN_BANK_CODE    VARCHAR2(100) NULL ,
	FOREIGN_TREASURY_CODE VARCHAR2(100) NULL ,
	DOMESTIC_BANK_CODE   VARCHAR2(100) NOT NULL ,
	DOMESTIC_TREASURY_CODE VARCHAR2(100) NOT NULL 
);



COMMENT ON TABLE EXP_INVESTOR IS 'Danh mục nhà đầu tư';




COMMENT ON COLUMN EXP_INVESTOR.INVESTOR_CODE IS 'Mã nhà đầu tư';




COMMENT ON COLUMN EXP_INVESTOR.INVESTOR_NAME IS 'Tên nhà đầu tư';




COMMENT ON COLUMN EXP_INVESTOR.DOMESTIC_ACCOUNT IS 'Số tài khoản Vốn trong nước';




COMMENT ON COLUMN EXP_INVESTOR.FOREIGN_ACCOUNT IS 'Số tài khoản Vốn nước ngoài';




COMMENT ON COLUMN EXP_INVESTOR.FOREIGN_BANK_CODE IS 'Ngân hàng mở Số tài khoản Vốn nước ngoài';




COMMENT ON COLUMN EXP_INVESTOR.FOREIGN_TREASURY_CODE IS 'Kho bạc mở Số tài khoản Vốn nước ngoài';




COMMENT ON COLUMN EXP_INVESTOR.DOMESTIC_BANK_CODE IS 'Ngân hàng mở Số tài khoản Vốn trong nước';




COMMENT ON COLUMN EXP_INVESTOR.DOMESTIC_TREASURY_CODE IS 'Kho bạc mở Số tài khoản Vốn trong nước';



CREATE UNIQUE INDEX EXP_INVESTOR_PK ON EXP_INVESTOR
(INVESTOR_CODE   ASC);



ALTER TABLE EXP_INVESTOR
	ADD CONSTRAINT  EXP_INVESTOR_PK PRIMARY KEY (INVESTOR_CODE);



CREATE TABLE EXP_PAYMENT_TYPE
(
	PAYMENT_TYPE_CODE    VARCHAR2(100) NOT NULL ,
	PAYMENT_TYPE_NAME    NVARCHAR2(500) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL 
);



COMMENT ON TABLE EXP_PAYMENT_TYPE IS 'Danh mục Loại thanh toán (Tạm ứng, thanh toán)';




COMMENT ON COLUMN EXP_PAYMENT_TYPE.PAYMENT_TYPE_CODE IS 'Mã loại thanh toán (Tạm ứng, thanh toán)';




COMMENT ON COLUMN EXP_PAYMENT_TYPE.PAYMENT_TYPE_NAME IS 'Loại thanh toán (Tạm ứng, thanh toán)';




COMMENT ON COLUMN EXP_PAYMENT_TYPE.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Có hiệu lực';




COMMENT ON COLUMN EXP_PAYMENT_TYPE.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_PAYMENT_TYPE.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_PAYMENT_TYPE.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_PAYMENT_TYPE.UPDATED_DATE IS 'Ngày cập nhật';




COMMENT ON COLUMN EXP_PAYMENT_TYPE.DESCRIPTION IS 'Mô tả';



CREATE UNIQUE INDEX EXP_PAYMENT_TYPE_PK ON EXP_PAYMENT_TYPE
(PAYMENT_TYPE_CODE   ASC);



ALTER TABLE EXP_PAYMENT_TYPE
	ADD CONSTRAINT  EXP_PAYMENT_TYPE_PK PRIMARY KEY (PAYMENT_TYPE_CODE);



CREATE TABLE EXP_PROJECT
(
	PROJECT_CODE         VARCHAR2(100) NOT NULL ,
	PROJECT_NAME         NVARCHAR2(500) NULL ,
	INVESTOR_CODE        VARCHAR2(100) NOT NULL ,
	PROJECT_MANAGEMENT_CODE VARCHAR2(100) NOT NULL ,
	PROJECT_TYPE_CODE    VARCHAR2(100) NOT NULL 
);



COMMENT ON TABLE EXP_PROJECT IS 'Danh mục dự án';




COMMENT ON COLUMN EXP_PROJECT.PROJECT_CODE IS 'Mã dự án';




COMMENT ON COLUMN EXP_PROJECT.PROJECT_NAME IS 'Tên dự án';




COMMENT ON COLUMN EXP_PROJECT.INVESTOR_CODE IS 'Mã nhà đầu tư';




COMMENT ON COLUMN EXP_PROJECT.PROJECT_MANAGEMENT_CODE IS 'Mã ban QLDA';




COMMENT ON COLUMN EXP_PROJECT.PROJECT_TYPE_CODE IS 'Mã loại dự án';



CREATE UNIQUE INDEX EXP_PROJECT_PK ON EXP_PROJECT
(PROJECT_CODE   ASC);



ALTER TABLE EXP_PROJECT
	ADD CONSTRAINT  EXP_PROJECT_PK PRIMARY KEY (PROJECT_CODE);



CREATE TABLE EXP_PROJECT_ITEM
(
	PROJECT_ITEM_CODE    VARCHAR2(100) NOT NULL ,
	PROJECT_ITEM_NAME    NVARCHAR2(500) NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMBER(1) NULL ,
	CREATED_BY           VARCHAR2(100) NULL ,
	CREATED_DATE         DATE NULL ,
	UPDATED_BY           VARCHAR2(100) NULL ,
	UPDATED_DATE         DATE NULL 
);



COMMENT ON TABLE EXP_PROJECT_ITEM IS 'Danh mục Hạng mục dự án';




COMMENT ON COLUMN EXP_PROJECT_ITEM.PROJECT_ITEM_CODE IS 'Mã hạng mục';




COMMENT ON COLUMN EXP_PROJECT_ITEM.PROJECT_ITEM_NAME IS 'Tên hạng mục';




COMMENT ON COLUMN EXP_PROJECT_ITEM.DESCRIPTION IS 'Mô tả';




COMMENT ON COLUMN EXP_PROJECT_ITEM.STATUS IS 'Trạng thái: 0-Không hiệu lực, 1-Hiệu lực';




COMMENT ON COLUMN EXP_PROJECT_ITEM.CREATED_BY IS 'Người tạo';




COMMENT ON COLUMN EXP_PROJECT_ITEM.CREATED_DATE IS 'Ngày tạo';




COMMENT ON COLUMN EXP_PROJECT_ITEM.UPDATED_BY IS 'Người cập nhật';




COMMENT ON COLUMN EXP_PROJECT_ITEM.UPDATED_DATE IS 'Ngày cập nhật';



CREATE UNIQUE INDEX EXP_PROJECT_ITEM_PK ON EXP_PROJECT_ITEM
(PROJECT_ITEM_CODE   ASC);



ALTER TABLE EXP_PROJECT_ITEM
	ADD CONSTRAINT  EXP_PROJECT_ITEM_PK PRIMARY KEY (PROJECT_ITEM_CODE);



CREATE TABLE EXP_PROJECT_MANAGEMENT
(
	PROJECT_MANAGEMENT_CODE VARCHAR2(100) NOT NULL ,
	PROJECT_MANAGEMENT_NAME NVARCHAR2(500) NULL 
);




COMMENT ON COLUMN EXP_PROJECT_MANAGEMENT.PROJECT_MANAGEMENT_CODE IS 'Mã ban QLDA';




COMMENT ON COLUMN EXP_PROJECT_MANAGEMENT.PROJECT_MANAGEMENT_NAME IS 'Tên ban QLDA';



CREATE UNIQUE INDEX EXP_PROJECT_MANAGEMENT_PK ON EXP_PROJECT_MANAGEMENT
(PROJECT_MANAGEMENT_CODE   ASC);



ALTER TABLE EXP_PROJECT_MANAGEMENT
	ADD CONSTRAINT  EXP_PROJECT_MANAGEMENT_PK PRIMARY KEY (PROJECT_MANAGEMENT_CODE);



CREATE TABLE EXP_PROJECT_SPECIFIC
(
	PROJECT_SPECIFIC_CODE VARCHAR2(100) NOT NULL ,
	PROJECT_SPECIFIC_NAME NVARCHAR2(500) NULL ,
	PROJECT_CODE         VARCHAR2(100) NOT NULL 
);



COMMENT ON TABLE EXP_PROJECT_SPECIFIC IS 'Danh mục dự án đặc thù';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.PROJECT_SPECIFIC_CODE IS 'Mã dự án đặc thù';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.PROJECT_SPECIFIC_NAME IS 'Tên dự án đặc thù';




COMMENT ON COLUMN EXP_PROJECT_SPECIFIC.PROJECT_CODE IS 'Mã dự án';



CREATE UNIQUE INDEX EXP_PROJECT_SPECIFIC_PK ON EXP_PROJECT_SPECIFIC
(PROJECT_SPECIFIC_CODE   ASC);



ALTER TABLE EXP_PROJECT_SPECIFIC
	ADD CONSTRAINT  EXP_PROJECT_SPECIFIC_PK PRIMARY KEY (PROJECT_SPECIFIC_CODE);



CREATE TABLE EXP_PROJECT_TYPE
(
	PROJECT_TYPE_CODE    VARCHAR2(100) NOT NULL ,
	PROJECT_TYPE_NAME    NVARCHAR2(500) NULL 
);



COMMENT ON TABLE EXP_PROJECT_TYPE IS 'Loại dự án';




COMMENT ON COLUMN EXP_PROJECT_TYPE.PROJECT_TYPE_CODE IS 'Mã loại dự án';




COMMENT ON COLUMN EXP_PROJECT_TYPE.PROJECT_TYPE_NAME IS 'Tên loại dự án';



CREATE UNIQUE INDEX EXP_PROJECT_TYPE_PK ON EXP_PROJECT_TYPE
(PROJECT_TYPE_CODE   ASC);



ALTER TABLE EXP_PROJECT_TYPE
	ADD CONSTRAINT  EXP_PROJECT_TYPE_PK PRIMARY KEY (PROJECT_TYPE_CODE);



CREATE TABLE EXP_WORKFLOW
(
	WORKFLOW_ID          NUMBER(18) NOT NULL ,
	WORKFLOW_NAME        NVARCHAR2(500) NULL ,
	WORKFLOW_CODE        VARCHAR2(100) NULL 
);



COMMENT ON TABLE EXP_WORKFLOW IS 'Bảng danh mục luồng phê duyệt';




COMMENT ON COLUMN EXP_WORKFLOW.WORKFLOW_ID IS 'Mã ID tự sinh từ sequence';




COMMENT ON COLUMN EXP_WORKFLOW.WORKFLOW_NAME IS 'Tên luồng phê duyệt';



CREATE UNIQUE INDEX EXP_WORKFLOW_PK ON EXP_WORKFLOW
(WORKFLOW_ID   ASC);



ALTER TABLE EXP_WORKFLOW
	ADD CONSTRAINT  EXP_WORKFLOW_PK PRIMARY KEY (WORKFLOW_ID);



CREATE TABLE PAYMENT_CHANNEL
(
	CHANNEL_ID           NUMERIC(19) NOT NULL ,
	CHANNEL_CODE         VARCHAR2(100) NOT NULL ,
	CHANNEL_NAME         NVARCHAR2(250) NOT NULL ,
	DESCRIPTION          NVARCHAR2(2000) NULL ,
	STATUS               NUMERIC(1) NOT NULL ,
	CREATED_BY           NUMERIC(19) NOT NULL ,
	CREATED_AT           TIMESTAMP NOT NULL ,
	UPDATED_BY           NUMERIC(19) NULL ,
	UPDATED_AT           TIMESTAMP NULL 
);



COMMENT ON TABLE PAYMENT_CHANNEL IS 'Bảng danh mục các kênh thanh toán';




COMMENT ON COLUMN PAYMENT_CHANNEL.CHANNEL_ID IS 'Khóa chính của bảng, sinh từ sequence, dùng để liên kết các bảng khác';




COMMENT ON COLUMN PAYMENT_CHANNEL.CHANNEL_CODE IS 'Mã kênh thanh toán, duy nhất';




COMMENT ON COLUMN PAYMENT_CHANNEL.CHANNEL_NAME IS 'Tên kênh thanh toán, dùng để hiển thị trên giao diện';




COMMENT ON COLUMN PAYMENT_CHANNEL.DESCRIPTION IS 'Mô tả chi tiết kênh thanh toán';




COMMENT ON COLUMN PAYMENT_CHANNEL.STATUS IS 'Trạng thái: 0-Không có hiệu lực, 1-Đang có hiệu lực, 2-Đã xóa';




COMMENT ON COLUMN PAYMENT_CHANNEL.CREATED_BY IS 'Mã ID tham chiếu của người tạo bản ghi';




COMMENT ON COLUMN PAYMENT_CHANNEL.CREATED_AT IS 'Thời điểm tạo bản ghi';




COMMENT ON COLUMN PAYMENT_CHANNEL.UPDATED_BY IS 'Mã ID tham chiếu của người cập nhật bản ghi cuối cùng';




COMMENT ON COLUMN PAYMENT_CHANNEL.UPDATED_AT IS 'Thời điểm cập nhật bản ghi cuối cùng';



CREATE UNIQUE INDEX PAYMENT_CHANNEL_PK ON PAYMENT_CHANNEL
(CHANNEL_ID   ASC);



ALTER TABLE PAYMENT_CHANNEL
	ADD CONSTRAINT  PAYMENT_CHANNEL_PK PRIMARY KEY (CHANNEL_ID);



CREATE UNIQUE INDEX UK_PAYMENT_CHANNEL_CODE ON PAYMENT_CHANNEL
(CHANNEL_CODE   ASC);



ALTER TABLE PAYMENT_CHANNEL
ADD CONSTRAINT  UK_PAYMENT_CHANNEL_CODE UNIQUE (CHANNEL_CODE);



ALTER TABLE COMMON_INVESTMENT_SOURCE
	ADD (CONSTRAINT R_55 FOREIGN KEY (SEGMENT_CODE) REFERENCES COMMON_GL_SEGMENT12 (SEGMENT_CODE));



ALTER TABLE EXP_APPROVAL_LOG
	ADD (CONSTRAINT R_34 FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (DOSSIER_ID));



ALTER TABLE EXP_ARCHIVE
	ADD (CONSTRAINT R_16 FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (DOSSIER_ID));



ALTER TABLE EXP_DIGITAL_SIGNED
	ADD (CONSTRAINT R_35 FOREIGN KEY (APPROVAL_LOG_ID) REFERENCES EXP_APPROVAL_LOG (APPROVAL_LOG_ID));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_18 FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (DOSSIER_ID));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_21 FOREIGN KEY (DOCUMENT_TEMPLATE_ID) REFERENCES EXP_DOCUMENT_TEMPLATE (DOCUMENT_TEMPLATE_ID));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_22 FOREIGN KEY (TREASURY_CODE) REFERENCES COMMON_TREASURY (TREASURY_CODE));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_29 FOREIGN KEY (PAYMENT_TYPE_CODE) REFERENCES EXP_PAYMENT_TYPE (PAYMENT_TYPE_CODE));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_38 FOREIGN KEY (CAPITAL_PLAN_TYPE_CODE) REFERENCES EXP_CAPITAL_PLAN_TYPE (CAPITAL_PLAN_TYPE_CODE));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_39 FOREIGN KEY (GUARANTEE_ID) REFERENCES EXP_GUARANTEE (GUARANTEE_ID));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_40 FOREIGN KEY (PROJECT_ITEM_CODE) REFERENCES EXP_PROJECT_ITEM (PROJECT_ITEM_CODE));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_44 FOREIGN KEY (CURRENCY_TYPE_CODE) REFERENCES EXP_CURRENCY_TYPE (CURRENCY_TYPE_CODE));



ALTER TABLE EXP_DOCUMENT
	ADD (CONSTRAINT R_46 FOREIGN KEY (EXCHANGE_RATE_TYPE_CODE) REFERENCES EXP_EXCHANGE_RATE_TYPE (EXCHANGE_RATE_TYPE_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_51 FOREIGN KEY (DOCUMENT_ID) REFERENCES EXP_DOCUMENT (DOCUMENT_ID));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_54 FOREIGN KEY (CAPITAL_YEAR) REFERENCES EXP_CAPITAL_YEAR (CAPITAL_YEAR));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_56 FOREIGN KEY (GL_SEGMENT2) REFERENCES COMMON_GL_SEGMENT2 (SEGMENT_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_58 FOREIGN KEY (GL_SEGMENT4) REFERENCES COMMON_GL_SEGMENT4 (SEGMENT_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_59 FOREIGN KEY (GL_SEGMENT5) REFERENCES COMMON_GL_SEGMENT5 (SEGMENT_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_60 FOREIGN KEY (GL_SEGMENT8) REFERENCES COMMON_GL_SEGMENT8 (SEGMENT_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_61 FOREIGN KEY (GL_SEGMENT9) REFERENCES COMMON_GL_SEGMENT9 (SEGMENT_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_62 FOREIGN KEY (GL_SEGMENT10) REFERENCES COMMON_GL_SEGMENT10 (SEGMENT_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_64 FOREIGN KEY (INVESTMENT_SOURCE_CODE, GL_SEGMENT12) REFERENCES COMMON_INVESTMENT_SOURCE (INVESTMENT_SOURCE_CODE, SEGMENT_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_65 FOREIGN KEY (GL_SEGMENT13) REFERENCES COMMON_GL_SEGMENT13 (SEGMENT_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_66 FOREIGN KEY (ALLOCATION_CRITERIA_CODE) REFERENCES COMMON_ALLOCATION_CRITERIA (ALLOCATION_CRITERIA_CODE));



ALTER TABLE EXP_DOCUMENT_LINE
	ADD (CONSTRAINT R_69 FOREIGN KEY (BENEFICIARY_BANK_CODE) REFERENCES COMMON_BANK (BANK_CODE));



ALTER TABLE EXP_DOCUMENT_TEMPLATE
	ADD (CONSTRAINT R_37 FOREIGN KEY (DOCUMENT_TYPE_CODE) REFERENCES EXP_DOCUMENT_TYPE (DOCUMENT_TYPE_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT R_1 FOREIGN KEY (DATA_SOURCE_CODE) REFERENCES EXP_DATA_SOURCE (DATA_SOURCE_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT R_12 FOREIGN KEY (STATE_CODE) REFERENCES COMMON_STATE (STATE_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT R_15 FOREIGN KEY (PROJECT_CODE) REFERENCES EXP_PROJECT (PROJECT_CODE));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT R_19 FOREIGN KEY (WORKFLOW_ID) REFERENCES EXP_WORKFLOW (WORKFLOW_ID));



ALTER TABLE EXP_DOSSIER
	ADD (CONSTRAINT R_33 FOREIGN KEY (TREASURY_CODE) REFERENCES COMMON_TREASURY (TREASURY_CODE));



ALTER TABLE EXP_DOSSIER_SLA
	ADD (CONSTRAINT R_36 FOREIGN KEY (DOSSIER_ID) REFERENCES EXP_DOSSIER (DOSSIER_ID));



ALTER TABLE EXP_EXCHANGE_RATE
	ADD (CONSTRAINT R_43 FOREIGN KEY (CURRENCY_TYPE_CODE) REFERENCES EXP_CURRENCY_TYPE (CURRENCY_TYPE_CODE));



ALTER TABLE EXP_INVESTOR
	ADD (CONSTRAINT R_155 FOREIGN KEY (DOMESTIC_BANK_CODE) REFERENCES COMMON_BANK (BANK_CODE));



ALTER TABLE EXP_INVESTOR
	ADD (CONSTRAINT R_156 FOREIGN KEY (DOMESTIC_TREASURY_CODE) REFERENCES COMMON_TREASURY (TREASURY_CODE));



ALTER TABLE EXP_PROJECT
	ADD (CONSTRAINT R_48 FOREIGN KEY (INVESTOR_CODE) REFERENCES EXP_INVESTOR (INVESTOR_CODE));



ALTER TABLE EXP_PROJECT
	ADD (CONSTRAINT R_49 FOREIGN KEY (PROJECT_MANAGEMENT_CODE) REFERENCES EXP_PROJECT_MANAGEMENT (PROJECT_MANAGEMENT_CODE));



ALTER TABLE EXP_PROJECT
	ADD (CONSTRAINT R_50 FOREIGN KEY (PROJECT_TYPE_CODE) REFERENCES EXP_PROJECT_TYPE (PROJECT_TYPE_CODE));



ALTER TABLE EXP_PROJECT_SPECIFIC
	ADD (CONSTRAINT R_47 FOREIGN KEY (PROJECT_CODE) REFERENCES EXP_PROJECT (PROJECT_CODE));


