<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.fis.vdbas.qtdc</groupId>
        <artifactId>vdbas-qttt-be</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>domain</artifactId>
    <packaging>jar</packaging>

    <name>domain</name>
    <description>Domain model: Entity &amp; Repository mapping từ schema Oracle</description>

    <dependencies>
        <dependency>
            <groupId>com.fis.vdbas.qtdc</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fis.vdbas</groupId>
            <artifactId>vdbas-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc11</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>





