/**
 * Selectors — form_detail.html  (CHI.CAPEX_DOSSIER — Chi tiết hồ sơ)
 * All data-testid constants extracted from the HTML source.
 * Generated by gen-ui-test skill.
 */
export const DSEL = {
  // ── Breadcrumb ────────────────────────────────────────────────
  BREADCRUMB_LINK_LIST: '[data-testid="breadcrumb-link-list"]',

  // ── Header buttons (top-right) ────────────────────────────────
  BTN_PRINT:    '[data-testid="btn-print"]',   // data-show-mode="view"
  BTN_EDIT:     '[data-testid="btn-edit"]',    // data-show-mode="view"; disabled unless DRAFT/CHECK_CANCELLED
  STATUS_BADGE: '[data-testid="status-badge"]',

  // ── Tab nav ───────────────────────────────────────────────────
  TAB_NAV:       '[data-testid="tab-nav"]',
  TAB_GENERAL:   '[data-testid="tab-general"]',   // always visible
  TAB_DOCUMENTS: '[data-testid="tab-documents"]', // hidden when mode=new
  TAB_ATTACH:    '[data-testid="tab-attach"]',
  TAB_HISTORY:   '[data-testid="tab-history"]',   // shortcut Alt+H
  TAB_APPROVAL:  '[data-testid="tab-approval"]',  // shortcut Alt+P

  // ── Tab panes ─────────────────────────────────────────────────
  PANE_GENERAL:   '[data-testid="pane-general"]',
  PANE_DOCUMENTS: '[data-testid="pane-documents"]',
  PANE_ATTACH:    '[data-testid="pane-attach"]',
  PANE_HISTORY:   '[data-testid="pane-history"]',
  PANE_APPROVAL:  '[data-testid="pane-approval"]',

  // ── Form fields — Thông tin chung ─────────────────────────────
  INPUT_DOSSIER_CODE:           '[data-testid="input-dossier-code"]',           // always readonly
  INPUT_SEND_DATE:              '[data-testid="input-send-date"]',
  INPUT_PROJECT_CODE:           '[data-testid="input-project-code"]',           // F4 lookup, cascades
  BTN_LOOKUP_PROJECT:           '[data-testid="btn-lookup-project"]',
  INPUT_PROJECT_NAME:           '[data-testid="input-project-name"]',           // readonly, auto-fill
  INPUT_PROJECT_SPECIFIC_CODE:  '[data-testid="input-project-specific-code"]',  // Military only
  BTN_LOOKUP_SPEC:              '[data-testid="btn-lookup-spec"]',
  INPUT_PROJECT_SPECIFIC_NAME:  '[data-testid="input-project-specific-name"]',  // Military only, readonly
  INPUT_PROJECT_MANAGEMENT_CODE:'[data-testid="input-project-management-code"]',// F4 lookup, cascades
  BTN_LOOKUP_BOARD:             '[data-testid="btn-lookup-board"]',
  INPUT_PROJECT_MANAGEMENT_NAME:'[data-testid="input-project-management-name"]',// readonly, auto-fill
  INPUT_STATE_CODE:             '[data-testid="input-state-code"]',             // <span> label
  INPUT_DATA_SOURCE_CODE:       '[data-testid="input-data-source-code"]',       // <select>
  ERROR_PROJECT_CODE:           '[data-testid="error-PROJECT_CODE"]',

  // ── Conditional groups (Military only) ───────────────────────
  GROUP_PROJECT_SPECIFIC_CODE: '#group-PROJECT_SPECIFIC_CODE',
  GROUP_PROJECT_SPECIFIC_NAME: '#group-PROJECT_SPECIFIC_NAME',

  // ── Documents tab ─────────────────────────────────────────────
  BTN_ADD_DOC:  '[data-testid="btn-add-doc"]',  // data-show-mode="edit"
  DOC_TABLE:    '[data-testid="doc-table"]',
  DOC_TBODY:    '[data-testid="doc-tbody"]',
  DOC_TOTAL_FX: '[data-testid="doc-total-fx"]',
  DOC_TOTAL:    '[data-testid="doc-total"]',
  DOC_CURRENCY: '[data-testid="doc-currency"]',

  // ── Attach tab ────────────────────────────────────────────────
  UPLOAD_ZONE_ATTACHMENTS: '[data-testid="upload-zone-attachments"]',
  BTN_UPLOAD:      '[data-testid="btn-upload"]',
  SELECT_DOC_TYPE: '[data-testid="select-doc-type"]',
  INPUT_NOTE:      '[data-testid="input-note"]',

  // ── History tab ───────────────────────────────────────────────
  HISTORY_TBODY: '[data-testid="history-tbody"]',

  // ── Approval workflow tab ─────────────────────────────────────
  APPROVAL_WORKFLOW: '[data-testid="approval-workflow"]',
  STEP_MAKER:        '[data-testid="step-maker"]',
  STEP_CHECKER:      '[data-testid="step-checker"]',
  STEP_APPROVER:     '[data-testid="step-approver"]',

  // ── Action bar ────────────────────────────────────────────────
  BTN_DELETE:     '[data-testid="btn-delete"]',     // data-show-mode="view", danger; disabled unless DRAFT
  BTN_CANCEL:     '[data-testid="btn-cancel"]',     // data-show-mode="new,edit"
  BTN_BACK:       '[data-testid="btn-back"]',       // data-show-mode="view"
  BTN_SAVE_DRAFT: '[data-testid="btn-save-draft"]', // data-show-mode="new,edit"
  BTN_SAVE:       '[data-testid="btn-save"]',       // data-show-mode="new"
  BTN_SAVE_EDIT:  '[data-testid="btn-save-edit"]',  // data-show-mode="edit"
  BTN_SUBMIT:     '[data-testid="btn-submit"]',     // data-show-mode="new,edit"; disabled until has docs

  // ── Modal: Delete Confirm ─────────────────────────────────────
  MODAL_DELETE_CONFIRM:   '[data-testid="modal-delete-confirm"]',
  INPUT_DELETE_REASON:    '[data-testid="input-delete-reason"]',
  DELETE_REASON_COUNTER:  '[data-testid="delete-reason-counter"]',
  INPUT_CONFIRM_REVIEWED: '[data-testid="input-confirm-reviewed"]',
  INPUT_DELETED_BY:       '[data-testid="input-deleted-by"]',
  INPUT_DELETED_DATE:     '[data-testid="input-deleted-date"]',
  BTN_CANCEL_DELETE:      '[data-testid="btn-cancel-delete"]',
  BTN_CONFIRM_DELETE:     '[data-testid="btn-confirm-delete"]',

  // ── Modal: Cancel Confirm ─────────────────────────────────────
  MODAL_CANCEL_CONFIRM: '[data-testid="modal-cancel-confirm"]',
  BTN_CONTINUE_EDIT:    '[data-testid="btn-continue-edit"]',
  BTN_CONFIRM_CANCEL:   '[data-testid="btn-confirm-cancel"]',

  // ── Modal: Lookup Project (LOV.01) ────────────────────────────
  MODAL_LOOKUP_PROJECT:     '[data-testid="modal-lookup-project"]',
  LOV_PROJECT_CODE:         '[data-testid="lov-project-code"]',
  LOV_PROJECT_NAME:         '[data-testid="lov-project-name"]',
  LOV_PROJECT_TYPE:         '[data-testid="lov-project-type"]',
  LOV_SEGMENT6:             '[data-testid="lov-segment6"]',
  LOV_TBODY:                '[data-testid="lov-tbody"]',
  LOV_COUNT:                '[data-testid="lov-count"]',
  BTN_CLOSE_LOOKUP_PROJECT: '[data-testid="btn-close-lookup-project"]',

  // ── Modal: Duplicate Warning (VAL-18) ─────────────────────────
  MODAL_DUPLICATE_WARNING: '[data-testid="modal-duplicate-warning"]',
  BTN_CANCEL_DUPLICATE:    '[data-testid="btn-cancel-duplicate"]',
  BTN_CONTINUE_DUPLICATE:  '[data-testid="btn-continue-duplicate"]',

  // ── Modal: Print Preview ──────────────────────────────────────
  MODAL_PRINT_PREVIEW:     '[data-testid="modal-print-preview"]',
  BTN_CLOSE_PRINT_PREVIEW: '[data-testid="btn-close-print-preview"]',
  BTN_PRINT_BROWSER:       '[data-testid="btn-print-browser"]',

  // ── Modal: Concurrent Edit ────────────────────────────────────
  MODAL_CONCURRENT:     '[data-testid="modal-concurrent"]',
  BTN_BACK_CONCURRENT:  '[data-testid="btn-back-concurrent"]',
  BTN_RETRY_CONCURRENT: '[data-testid="btn-retry-concurrent"]',

  // ── Modal: Outside Hour ───────────────────────────────────────
  MODAL_OUTSIDE_HOUR: '[data-testid="modal-outside-hour"]',
  // TODO: "Đã hiểu, tiếp tục" button has no data-testid → add data-testid="btn-dismiss-outside-hour" to HTML

  // ── Fallback selectors (elements lacking data-testid) ─────────
  // '#dialog-session-expired'   — no data-testid (session expired dialog)
  // '.data-table tbody' (attach tab attachment list)
  // '#approval-detail'          — approval rejection reason text area
} as const
